### DISCUSSION TITLE
ETCD multimaster cluster without kubernetes

### DISCUSSION THREAD

**Discussion by DemianTinkiel** [etcd-io/etcd#14193] [Q&A]
I'm setting up an ETCD cluster, unrelated to kubernetes. I would like to set it up such that there is 2 active leaders. Is there a way to achieve this? I have the following docker-compose
```
version: '3.7'

services:
  etcd1:
    hostname: "etcd1"
    networks:
      - nw1
    image: docker.io/bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ELECTION_TIMEOUT=2000
  etcd2:
    hostname: "etcd2"
    networks:
      - nw1
    image: docker.io/bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_ELECTION_TIMEOUT=2000


networks:
  nw1:
    name: "nw1"
```  
   Starting this I see one of the nodes will be elected as leader but disconnecting them from each other via `docker network disconnect nw1 etcd2` doesn't make either become their own leader. I tried the same with 6 nodes (with a split in the middle such that it would become 2 clusters of 3), same result.

I tried searching for this but all references seem to point to a multimaster kubernetes cluster. Is there a way to do it without kubernetes?
