### DISCUSSION TITLE
How to get a etcd service in the github workflow

### DISCUSSION THREAD

**Discussion by SimFG** [etcd-io/etcd#16504] [Q&A] [answered]
I try to do this like:
```
services:
      etcd:
        image: quay.io/coreos/etcd:v3.5.5
        ports:
          - 2379:2379
```

but in the action, i can't use it.
![image](https://github.com/etcd-io/etcd/assets/21985684/f2ad7cde-ecd9-42ab-b6cf-473485a9e784)
![image](https://github.com/etcd-io/etcd/assets/21985684/0b3105d4-b304-4138-9fd9-b83802ec6116)

**Comment by jmhbnz** [comment]
Hey @SimFG - Thanks for your question.  Can you please confirm if the github actions job you are running that unable to connect to the etcd service container is also itself running in a container?

This would be denoted by something like

```yaml
jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:16-bullseye
```

If so, the etcd service container you are spinning up will not be available on `localhost:2379`, instead it would be available on the hostname of the service container which in your case based on the yaml snippet would be `etcd:2379`. Refer https://docs.github.com/en/actions/using-containerized-services/about-service-containers#communicating-with-service-containers.

> When you run jobs in a container, GitHub connects service containers to the job using Docker's user-defined bridge networks. For more information, see "[Use bridge networks](https://docs.docker.com/network/bridge/)" in the Docker documentation.
>
> Running the job and services in a container simplifies network access. You can access a service container using the label you configure in the workflow. The hostname of the service container is automatically mapped to the label name. For example, if you create a service container with the label redis, the hostname of the service container is redis.

If this doesn't address the issue please provide your actions workflow yaml file, redacted if required.

**Comment by SimFG** [comment]
@jmhbnz thanks your reply.

The following is the entire workflow file. Mysql can serve normally, but etcd can’t. It seems that some configuration is missing.

```yaml
jobs:
  build:
    name: Unittest AMD64 Ubuntu ${{ matrix.ubuntu }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        ubuntu: [18.04]
    env:
      UBUNTU: ${{ matrix.ubuntu }}
    services:
      mysql:
        image: mysql:5.7.42
        env:
          MYSQL_ROOT_PASSWORD: xxxx
          MYSQL_DATABASE: xxxx
        ports:
          - 3306:3306
      etcd:
        image: quay.io/coreos/etcd:v3.5.5
        ports:
          - 2379:2379
    steps:
      - uses: actions/checkout@v3
      - name: Run Unittest
        run: make test-go
```

**Reply by jmhbnz** [reply, marked as answer]
Thanks for the full example. I can see the issue now.

By default, etcd listens on `http://localhost:2379`.  However if we are trying to access the etcd instance from outside a docker container, we need to ensure it listens on `http://0.0.0.0:2379` inside the container.

This is easy enough to do as follows:

```yaml

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      etcd:
        image: quay.io/coreos/etcd:v3.5.5
        env:
          - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
          - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
        ports:
          - 2379:2379
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: |

          # Confirm etcd container is running
          docker ps
          
          # Review logs to confirm etcd container started as expected
          docker logs "${{ job.services.etcd.id }}"

          # Test doing stuff directly inside the etcd container
          docker exec "${{ job.services.etcd.id }}" etcdctl put foo bar

          # Test doing stuff outside the etcd container
          curl -v localhost:2379/metrics
```
