### DISCUSSION TITLE
ETCD docker-compose runtime configuration

### DISCUSSION THREAD

**Discussion by MatthewComtois** [etcd-io/etcd#17011] [Q&A] [answered]
Hi, I’m pretty new to etcd and I have difficulty finding information about this kind of configuration in docker. I’m not even certain if I what I want to do is even possible. I’m using docker-compose to start a three node cluster of etcd. My node are being attack by a service similar to a choas monkey. The initial configuration seem to be working fine. I can interact with it using dotnet-etcd. The problem is when one of the node restart, it only start etcd in the background but does not join back the cluster. The only thing that kind if helped is the documentation about runtime reconfiguration (https://etcd.io/docs/v3.3/op-guide/runtime-configuration/) but it mainly involve doing manual reconfiguration and not automatic. 

My question are: 

Is their a way that to automatically delete node that has become inactive?

Also, do I always need to change my environnement variable to rejoin the cluster or I can just keep the same env variable from the initialization of the cluster.

thank you

**Comment by jmhbnz** [comment]
Hey @MatthewComtois - Thanks for your question. Are you using docker volumes to persist the data directory of your etcd members?

If not, this could potentially explain why they are not coming back up with the expected configuration after being disrupted by your chaos monkey.

For an example of a docker configuration for etcd that uses volumes refer to: https://github.com/etcd-io/etcd/discussions/16138#discussioncomment-6287817. 

Just to be clear on why this is important, once an etcd member is restarted, it is definitely expected that it should rejoin whichever cluster it is already a member of provided it gets started with the same data directory it used to have and the right parameters.

Feel free to post your docker-compose file if you need more help.

**Comment by MatthewComtois** [comment]
Hi, 
Thank you for your answer.

I did configure with a volume, but until the whole cluster is down, it doesn't rejoin it.  It does a loop with this error saying it  has already been bootstrapped.

Also, I'm using the arm64 image because I'm running it in Docker with Apple Silicon, but I don't know if it's necessary. 

<img width="1636" alt="image" src="https://github.com/etcd-io/etcd/assets/75453512/bf902dbb-4a9a-4281-9f74-9226338529e1">


  etcd1:
    image: quay.io/coreos/etcd:v3.5.10-arm64
    container_name: etcd1
    hostname: etcd1
    restart: always
    command:
      - etcd
      - --name=etcd1
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd1:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd1:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    ports:
      - "2379:2379"
    volumes:
      - ./store/etcd1/data:/etcd_data
  etcd2:
    image: quay.io/coreos/etcd:v3.5.10-arm64
    container_name: etcd2
    hostname: etcd2
    restart: always
    command:
      - etcd
      - --name=etcd2
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd2:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd2:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    ports:
      - "22379:2379"
    volumes:
      - ./store/etcd2/data:/etcd_data
  etcd3:
    image: quay.io/coreos/etcd:v3.5.10-arm64
    container_name: etcd3
    hostname: etcd3
    restart: always
    command: 
      - etcd
      - --name=etcd3
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd3:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd3:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
    ports:
      - "32379:2379"
    volumes:
      - ./store/etcd3/data:/etcd_data

**Reply by jmhbnz** [reply]
Hey @MatthewComtois - Thanks for the update.  The `- --initial-cluster-state=new` flag is what is causing the issue I believe.  This should only be set the first time the member starts, after that the flag should be changed to `existing`.  In this example we can just omit the flag.

Here is a working setup at my end:

```bash
# Write the compose file
cat << EOF > docker-compose.yaml
---
services:
  etcd1:
    image: quay.io/coreos/etcd:v3.5.10-amd64
    container_name: etcd1
    hostname: etcd1
    restart: always
    command: |
      etcd
      --name=etcd1
      --data-dir=data.etcd
      --advertise-client-urls=http://etcd1:2379
      --listen-client-urls=http://0.0.0.0:2379
      --initial-advertise-peer-urls=http://etcd1:2380
      --listen-peer-urls=http://0.0.0.0:2380
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --initial-cluster-token=etcd-cluster-1
    ports:
      - "2379:2379"
    volumes:
      - ./store/etcd1/data:/etcd_data
  etcd2:
    image: quay.io/coreos/etcd:v3.5.10-amd64
    container_name: etcd2
    hostname: etcd2
    restart: always
    command: |
      etcd
      --name=etcd2
      --data-dir=data.etcd
      --advertise-client-urls=http://etcd2:2379
      --listen-client-urls=http://0.0.0.0:2379
      --initial-advertise-peer-urls=http://etcd2:2380
      --listen-peer-urls=http://0.0.0.0:2380
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --initial-cluster-token=etcd-cluster-1
    ports:
      - "22379:2379"
    volumes:
      - ./store/etcd2/data:/etcd_data
  etcd3:
    image: quay.io/coreos/etcd:v3.5.10-amd64
    container_name: etcd3
    hostname: etcd3
    restart: always
    command: |
      etcd
      --name=etcd3
      --data-dir=data.etcd
      --advertise-client-urls=http://etcd3:2379
      --listen-client-urls=http://0.0.0.0:2379
      --initial-advertise-peer-urls=http://etcd3:2380
      --listen-peer-urls=http://0.0.0.0:2380
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --initial-cluster-token=etcd-cluster-1
    ports:
      - "32379:2379"
    volumes:
      - ./store/etcd3/data:/etcd_data
EOF

# Start the cluster 
docker compose up -d && sleep 5s

# Check containers 
docker ps
docker exec -it etcd1 etcdctl endpoint status --endpoints etcd1:2379,etcd2:2379,etcd3:2379 -w table && sleep 5s

# Restart the etcd1 container
docker restart etcd1 && sleep 5s

# Check logs and cluster status
docker logs etcd1
docker exec -it etcd1 etcdctl endpoint status --endpoints etcd1:2379,etcd2:2379,etcd3:2379 -w table
```

Note: I adjusted the cpu architecture of the image to `amd64` for my local environment.

**Reply by MatthewComtois** [reply]
Thank you, I will test this tomorrow morning and give you an update

**Reply by MatthewComtois** [reply]
Hi, I tried with removing the - --initial-cluster-state=new. I purged my docker and delete the old volume. But, I still get the same error. Here is a fuller output. It looks like it's using initial-cluster-state as new anyway.

<img width="1632" alt="image" src="https://github.com/etcd-io/etcd/assets/75453512/a69a9a7a-8b41-4e97-8952-19ca20e80047">
<img width="1651" alt="image" src="https://github.com/etcd-io/etcd/assets/75453512/2ea589cc-b5df-4c2a-8fca-c7ae10e48fcb">
<img width="317" alt="image" src="https://github.com/etcd-io/etcd/assets/75453512/541586fb-6c9e-4ccf-b6b8-f1466ba2a231">

and here is my updated docker compose file. I switch to the basic the non-arm version for testing but it's does look like it does any difference.

```yaml
  etcd1:
    image: quay.io/coreos/etcd:v3.5.10
    container_name: etcd1
    hostname: etcd1
    restart: always
    command:
      - etcd
      - --name=etcd1
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd1:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd1:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-token=etcd-cluster-1
    ports:
      - "2379:2379"
    volumes:
      - ./store/etcd1/data:/etcd_data
  etcd2:
    image: quay.io/coreos/etcd:v3.5.10
    container_name: etcd2
    hostname: etcd2
    restart: always
    command:
      - etcd
      - --name=etcd2
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd2:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd2:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-token=etcd-cluster-1
    ports:
      - "22379:2379"
    volumes:
      - ./store/etcd2/data:/etcd_data
  etcd3:
    image: quay.io/coreos/etcd:v3.5.10
    container_name: etcd3
    hostname: etcd3
    restart: always
    command: 
      - etcd
      - --name=etcd3
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd3:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd3:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-token=etcd-cluster-1
    ports:
      - "32379:2379"
    volumes:
      - ./store/etcd3/data:/etcd_data
```
