### DISCUSSION TITLE
What memory limit should i set for etcd?

### DISCUSSION THREAD

**Discussion by V0idk** [etcd-io/etcd#17764] [Q&A] [answered]
### What would you like to be added?

I am deploy etcd by k8s pod, but i have an oom probelm when i set memory limit 12Gi: 

```yaml
apiVersion: v1
kind: Pod
    resources:
      limits:
        cpu: "4"
        memory: 12Gi
```

etcd command is: 

`etcd  --snapshot-count=10000 --auto-compaction-retention=24  --max-request-bytes=10485760 --quota-backend-bytes=858993459 ...`

my question is what is the proberly memory limit for the above command? 

Is `limit = quota-backend-bytes + ?` ok?  but why 12Gi is not enough for quota-backend-bytes 8g?

or Is `limit = quota-backend-bytes * 2` ok?  

### Why is this needed?

What memory limit should i set for etcd?
