### DISCUSSION TITLE
etcd leader changed

### DISCUSSION THREAD

**Discussion by sowabdoul** [etcd-io/etcd#18438] [Q&A]
I need help with an issue in my Kubernetes cluster, which is set up with 3 control-plane nodes and 3 worker nodes using kubeadm. The etcd pods are located on the control-plane nodes. Initially, everything was working fine, but after a few months of usage, I've started encountering errors in etcd that are causing other pods to crash.

The error message I see is:

```javascript
Error from server: etcdserver: leader changed
```

After researching online, I added the following options to my etcd manifests:

```yaml
etcd.yaml
---
spec:
  containers:
  - command:
    - --snapshot-count=10000
    - --heartbeat-interval=500
    - --election-timeout=2500
    - --pre-vote=true
    ...
    resources: {}
```
While the frequency of errors has decreased, they are still persisting, and it feels like I've only moved the problem rather than fully resolving it.

Currently, the `/var/lib/etcd` directory is mounted on the system partition. I want to mount a new partition on `sdb` and then move `etcd` to it. Do you think this will resolve the performance issues with etcd?

Could you please help me with this issue?
