### ISSUE TITLE
the problem of --log-outputs in new version(3.4)

### ISSUE THREAD

**Issue by johncming** [etcd-io/etcd#10303]
first, set env
```
export ETCD_LOGGER=zap
export ETCD_DEBUG=true
```

then, got error

```
2018-12-05 06:09:48.442068 E | etcdmain: error verifying flags, '--log-outputs=default' is not supported for v3.4 during zap logger migraion (use 'journal', 'stderr', 'stdout', etc.). See 'etcd --help'.
```
Check the code

https://github.com/etcd-io/etcd/blob/3f014267129898b743ab1d8ab952c44364f69534/embed/config_logging.go#L154-L155

There's a question why not just specify a logger, like this:

```go
			case DefaultLogOutput:
				outputPaths[StdErrLogOutput] = struct{}{}
				errOutputPaths[StdErrLogOutput] = struct{}{}
```

If necessary, I can help modify it.

In addition, the configuration in document needs to be updated.

**Comment by gyuho** [comment]
I wanted to make sure when used with `zap`, users explicitly specify where to output the logs.

Have you tried

```
etcd --logger=zap --log-outputs=stderr
```

?

**Comment by johncming** [comment]
The problem is mainly an error prompt, not refer to the specific output location which is an example to the situation.

Problem reproduction environment

```
version: '3.7'

services:
  etcd1:
    image: site:5000/myetcd
    ports:
      - 2379:2379
    networks:
      - etcd
    container_name: etcd1
    hostname: etcd1
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd1
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd1:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd1:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
    environment:
      - "ETCD_LOGGER=zap"
      - "ETCD_DEBUG=true"

networks:
  etcd:
    name: etcd
    driver: overlay
    attachable: true
```

output:

```
2018-12-06 00:20:59.290526 I | pkg/flags: recognized and used environment variable ETCD_DEBUG=true,
2018-12-06 00:20:59.290713 I | pkg/flags: recognized and used environment variable ETCD_LOGGER=zap,
2018-12-06 00:20:59.290780 E | etcdmain: error verifying flags, '--log-outputs=default' is not supported for v3.4 during zap logger migraion (use 'journal', 'stderr', 'stdout', etc.). See 'etcd --help'.
```
