### ISSUE TITLE
ETCD mirror is growing continously

### ISSUE THREAD

**Issue by ghost** [etcd-io/etcd#11168]
**ETCD version: 3.3.10**

#### ETCD mirror is growing continously and I have no ideas how to avoid this.
![Imgur](https://i.imgur.com/V8tDcv1.jpg)

I am using statis POD manifest to start the mirroring instance.
**Here are it confiiguration:**
```
    command:
    - /usr/local/bin/etcdctl 
    - make-mirror
    - --no-dest-prefix=true
    - http://1.2.3.4:2379
    # --------------------------------
    env:
    - name: ETCDCTL_API
      value: "3"
    - name: ETCDCTL_DEBUG
      value: "false"
    - name: ETCDCTL_DIAL_TIMEOUT
      value: "2s"
    - name: ETCDCTL_KEEPALIVE_TIME
      value: "2s"
    - name: ETCDCTL_KEEPALIVE_TIMEOUT
      value: "6s"
    - name: ETCDCTL_ENDPOINTS
      value: "http://cluster-etcd-endpoints:2379"
    - name: ETCDCTL_INSECURE_DISCOVERY
      value: "true"
    - name: ETCDCTL_INSECURE_TRANSPORT
      value: "true"
    - name: ETCDCTL_INSECURE_SKIP_TLS_VERIFY
      value: "true"
```

**It is mirroring data to the standalone instance which has next parameters:**

```
ETCD_NAME=etcd4
ETCD_INITIAL_CLUSTER_TOKEN=token
ETCD_INITIAL_CLUSTER_STATE=new
ETCD_DATA_DIR=/var/lib/etcd
ETCD_METRICS=basic
ETCD_PROXY=off
# --------------------------------------------------
ETCD_ADVERTISE_CLIENT_URLS=http://bla-bla-bla:2379
ETCD_INITIAL_ADVERTISE_PEER_URLS=http://bla-bla-bla:2380
ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
ETCD_INITIAL_CLUSTER=etcd4=http://bla-bla-bla:2380
# --------------------------------------------------
ETCD_AUTO_COMPACTION_RETENTION=8
ETCD_HEARTBEAT_INTERVAL=250
ETCD_QUOTA_BACKEND_BYTES=4294967296
ETCD_ELECTION_TIMEOUT=5000
ETCD_SNAPSHOT_COUNT=10000
# --------------------------------------------------
ETCD_AUTO_TLS=false
ETCD_PEER_AUTO_TLS=false
ETCD_CLIENT_CERT_AUTH=false
ETCD_PEER_CLIENT_CERT_AUTH=false
```

- I've tried multiplie times to clear all data directory and start mirror endpoint from the scratch
- Recreated many times mirroring POD as well
Everything without success

Maybe anyone can help with this. Thanks in advance.
