### ISSUE TITLE
docker swarm  cant start etcd container with healtcheck enabled 

### ISSUE THREAD

**Issue by mavenir-labs** [etcd-io/etcd#11340]
Hi ,
I am trying to start a  3 node ETCD cluster in docker SWARM  environemnt  using stack .
when service healtheck is enables, docker fails to start containers .
maybe it a typo in Stack yaml or misconfiguration of test command, I dont know.

the health check part looks like this,

    healthcheck:
         disable: true
        test: ["CMD-SHELL","/usr/bin/curl", "http://127.0.0.1:2379/health"]
        interval: 10s
        timeout: 10s
        retries: 3
        start_period: 10s

if this is Not the right way to do it, i'd appriciate  some guidance.

Avi.

**Comment by mavenir-labs** [comment]
the  ' disable: true '   was pasted  by mistake  to the  issue .

**Comment by flavienbwk** [comment]
I got this config working :

```yml
    healthcheck:
      test: ["CMD", "curl", "http://127.0.0.1:2379/health"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 5s
```
