### ISSUE TITLE
Unable to Change Raft Log Level From Info to Warn

### ISSUE THREAD

**Issue by petermetz** [etcd-io/etcd#11407]
### Problem Statement 
Can't get raft logs to be on `warn` level, they seem to be stuck on `info`.

If you see the first two lines of the log, it shows that etcd `recognized and used` my env. vars through which I configured the logging to have the global log level set to `warn` and also tried the deprecated pkg specific log level to explicitly set the `raft` package's log level to `warn`.

Then you can observe at the end of the logs that raft is still happily logging at `info` level messages.
 
I'm using the public docker image/tag combo `bitnami/etcd:3.4.3`

Also tried to specify the log level name with caps `WARN`, but it doesn't work either, still logs that it was unable to parse it:
```sh
etcd2_1              | 2019-11-29 04:24:32.748057 W | embed: couldn't parse log level string: couldn't parse log level WARN, continuing with default levels
```

### Etcd Logs

```sh
etcd3_1              | 2019-11-29 03:59:04.407137 I | pkg/flags: recognized and used environment variable ETCD_LOG_LEVEL=warn
etcd3_1              | 2019-11-29 03:59:04.407142 I | pkg/flags: recognized and used environment variable ETCD_LOG_PACKAGE_LEVELS=raft=warn
etcd3_1              | 2019-11-29 03:59:04.407153 I | pkg/flags: recognized and used environment variable ETCD_NAME=etcd3
etcd3_1              | [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
etcd3_1              | [WARNING] Deprecated '--log-package-levels=raft=warn' flag is set; use '--logger=zap' flag instead
etcd3_1              | 2019-11-29 03:59:04.407211 W | embed: couldn't parse log level string: couldn't parse log level warn, continuing with default levels
etcd3_1              | [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
etcd3_1              | [WARNING] Deprecated '--log-package-levels=raft=warn' flag is set; use '--logger=zap' flag instead
etcd3_1              | 2019-11-29 03:59:04.407257 W | embed: couldn't parse log level string: couldn't parse log level warn, continuing with default levels
etcd3_1              | {"level":"info","ts":1574999944.4677496,"caller":"netutil/netutil.go:112","msg":"resolved URL Host","url":"http://etcd3:2380","host":"etcd3:2380","resolved-addr":"192.20.0.52:2380"}     etcd3_1              | {"level":"info","ts":1574999944.4684129,"caller":"netutil/netutil.go:112","msg":"resolved URL Host","url":"http://etcd3:2380","host":"etcd3:2380","resolved-addr":"192.20.0.52:2380"}     etcd3_1              | raft2019/11/29 03:59:04 INFO: bd388e7810915853 switched to configuration voters=()
etcd3_1              | raft2019/11/29 03:59:04 INFO: bd388e7810915853 became follower at term 0
etcd3_1              | raft2019/11/29 03:59:04 INFO: newRaft bd388e7810915853 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
etcd3_1              | raft2019/11/29 03:59:04 INFO: bd388e7810915853 became follower at term 1
```

### Repro docker-compose.yml

```yaml
version: "2"

services:

  etcd1:
    image: bitnami/etcd:3.4.3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_LOG_LEVEL=warn
      - ETCD_LOG_PACKAGE_LEVELS=raft=warn

  etcd2:
    image: bitnami/etcd:3.4.3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_LOG_LEVEL=warn
      - ETCD_LOG_PACKAGE_LEVELS=raft=warn

  etcd3:
    image: bitnami/etcd:3.4.3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_LOG_LEVEL=warn
      - ETCD_LOG_PACKAGE_LEVELS=raft=warn

```
