### ISSUE TITLE
question about listen-metric-urls option in kube-etcd

### ISSUE THREAD

**Issue by Hokwang** [etcd-io/etcd#11446]
Hello.

I want to see etcd metric in prometheus.

Now, etcd's option is
```
cat /etc/kubernetes/manifests/etcd.yaml
...
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://<masterip>:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=https://<masterip>:2380
    - --initial-cluster=<hostname>=https://<masterip>:2380
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://<masterip>:2379
    - --listen-peer-urls=https://<masterip>:2380
    - --name=<hostname>
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
```

For easiest using, I want to add `--listen-metric-urls=http://<masterip>:2379` option,
but is this right syntax?

I can't find example of this.

Thanks,
