### ISSUE TITLE
Range Query Sample

### ISSUE THREAD

**Issue by kieronlanning** [etcd-io/etcd#11852]
I'm trying to figure out a way of being able to do a range query based on something like this:

```
data:
   foo1: value
   foo2: value
   foo3: value
   foo4: value
   foo5: value
```

I'd like to be able to query that data like this:

Get everything from foo2 to foo4 (specific end result), returning:
```
data:
   foo3: value
   foo4: value
```

Or, everything from foo2 onwards (no end) for example:
```
data:
   foo3: value
   foo4: value
   foo5: value
```

The `foo` keys have no end.
