### ISSUE TITLE
Metrics not following Prometheus best practices

### ISSUE THREAD

**Issue by dgrisonnet** [etcd-io/etcd#12120]
**Description**

I ran [promlint](https://godoc.org/github.com/prometheus/client_golang/prometheus/testutil/promlint) accross all metrics exposed in OpenShift and noticed that some metrics from etcd were not following Prometheus [best practices](https://prometheus.io/docs/practices/naming/).
From this run, the following metrics exposed by etcd were reported:

```yaml
etcd_debugging_mvcc_keys_total:
  - non-counter metrics should not have "_total" suffix
etcd_debugging_mvcc_pending_events_total:
  - non-counter metrics should not have "_total" suffix
etcd_debugging_mvcc_slow_watcher_total:
  - non-counter metrics should not have "_total" suffix
etcd_debugging_mvcc_watch_stream_total:
  - non-counter metrics should not have "_total" suffix
etcd_debugging_mvcc_watcher_total:
  - non-counter metrics should not have "_total" suffix
etcd_disk_wal_write_bytes_total:
  - non-counter metrics should not have "_total" suffix
etcd_grpc_proxy_cache_hits_total:
  - non-counter metrics should not have "_total" suffix
etcd_grpc_proxy_cache_keys_total:
  - non-counter metrics should not have "_total" suffix
etcd_grpc_proxy_cache_misses_total:
  - non-counter metrics should not have "_total" suffix
etcd_grpc_proxy_watchers_coalescing_total:
  - non-counter metrics should not have "_total" suffix
etcd_server_health_failures:
  - counter metrics should have "_total" suffix
etcd_server_health_success:
  - counter metrics should have "_total" suffix
etcd_server_learner_promote_successes:
  - counter metrics should have "_total" suffix
etcd_server_proposals_applied_total:
  - non-counter metrics should not have "_total" suffix
etcd_server_proposals_committed_total:
  - non-counter metrics should not have "_total" suffix
etcd_server_snapshot_apply_in_progress_total:
  - non-counter metrics should not have "_total" suffix
```

**Suggestion**

From the report, we can notice 2 different types of lint errors:
- counters not having a "_total" suffix
- gauges having a "_total" suffix

Thus, in order to follow the best practices, I would suggest the following changes:

[etcd_debugging_mvcc_keys_total](https://github.com/etcd-io/etcd/blob/master/mvcc/metrics.go#L86-L92) --> etcd_debugging_mvcc_keys
[etcd_debugging_mvcc_pending_events_total](https://github.com/etcd-io/etcd/blob/master/mvcc/metrics.go#L126-L132) --> etcd_debugging_mvcc_pending_events
[etcd_debugging_mvcc_slow_watcher_total](https://github.com/etcd-io/etcd/blob/master/mvcc/metrics.go#L110-L116) --> etcd_debugging_mvcc_slow_watchers
[etcd_debugging_mvcc_watch_stream_total](https://github.com/etcd-io/etcd/blob/master/mvcc/metrics.go#L94-L100) --> etcd_debugging_mvcc_watch_streams
[etcd_debugging_mvcc_watcher_total](https://github.com/etcd-io/etcd/blob/master/mvcc/metrics.go#L102-L108) --> etcd_debugging_mvcc_watchers
[etcd_disk_wal_write_bytes_total](https://github.com/etcd-io/etcd/blob/master/wal/metrics.go#L31-L36) --> etcd_disk_wal_bytes
[etcd_grpc_proxy_cache_hits_total](https://github.com/etcd-io/etcd/blob/master/proxy/grpcproxy/metrics.go#L49-L54) --> etcd_grpc_proxy_cache_hits
[etcd_grpc_proxy_cache_keys_total](https://github.com/etcd-io/etcd/blob/master/proxy/grpcproxy/metrics.go#L43-L48) --> etcd_grpc_proxy_cache_keys
[etcd_grpc_proxy_cache_misses_total](https://github.com/etcd-io/etcd/blob/master/proxy/grpcproxy/metrics.go#L55-L60) --> etcd_grpc_proxy_cache_misses
[etcd_grpc_proxy_watchers_coalescing_total](https://github.com/etcd-io/etcd/blob/master/proxy/grpcproxy/metrics.go#L31-L36) --> etcd_grpc_proxy_watchers_coalescing
[etcd_server_health_failures](https://github.com/etcd-io/etcd/blob/master/etcdserver/api/etcdhttp/metrics.go#L77-L82) --> etcd_server_health_failures_total
[etcd_server_health_success](https://github.com/etcd-io/etcd/blob/master/etcdserver/api/etcdhttp/metrics.go#L71-L76) --> etcd_server_health_successes_total
[etcd_server_learner_promote_successes](https://github.com/etcd-io/etcd/blob/master/etcdserver/metrics.go#L61-L66) --> etcd_server_learner_promote_successes_total
[etcd_server_proposals_applied_total](https://github.com/etcd-io/etcd/blob/master/etcdserver/metrics.go#L91-L96) --> etcd_server_proposals_applied
[etcd_server_proposals_committed_total](https://github.com/etcd-io/etcd/blob/master/etcdserver/metrics.go#L85-L90) --> etcd_server_proposals_committed
[etcd_server_snapshot_apply_in_progress_total](https://github.com/etcd-io/etcd/blob/master/etcdserver/metrics.go#L79-L84) --> etcd_server_snapshot_apply_in_progress
