### ISSUE TITLE
rejected connection from "127.0.0.1:55084" (error "EOF", ServerName "localhost") in logs

### ISSUE THREAD

**Issue by rajatjindal** [etcd-io/etcd#12217]
Hello,

we are using etcd as backend store for our cilium deployment. Recently we upgraded from 3.2.x to 3.3.x (and tried 3.4.x as well), and started to see following msg in logs whenever readiness/liveness probes are executed:

```
rejected connection from "127.0.0.1:55084" (error "EOF", ServerName "localhost")
```

We tried debugging this, and could not find the root cause, but did find a workaround. We are reporting the issue so that it can be tracked and if someone happen to find the root cause, we can fix it.

**etcd start command (managed by etcd-operator):**

```
    - /usr/local/bin/etcd
    - --data-dir=/var/etcd/data
    - --name=cilium-etcd-cluster-27b5x9hbqf
    - --initial-advertise-peer-urls=https://cilium-etcd-cluster-27b5x9hbqf.cilium-etcd-cluster.kube-system.svc:2380
    - --listen-peer-urls=https://0.0.0.0:2380
    - --listen-client-urls=https://0.0.0.0:2379
    - --advertise-client-urls=https://cilium-etcd-cluster-27b5x9hbqf.cilium-etcd-cluster.kube-system.svc:2379
    - --initial-cluster=cilium-etcd-cluster-27b5x9hbqf=https://cilium-etcd-cluster-27b5x9hbqf.cilium-etcd-cluster.kube-system.svc:2380
    - --initial-cluster-state=new
    - --peer-client-cert-auth=true
    - --peer-trusted-ca-file=/etc/etcdtls/member/peer-tls/peer-ca.crt
    - --peer-cert-file=/etc/etcdtls/member/peer-tls/peer.crt
    - --peer-key-file=/etc/etcdtls/member/peer-tls/peer.key
    - --client-cert-auth=true
    - --trusted-ca-file=/etc/etcdtls/member/server-tls/server-ca.crt
    - --cert-file=/etc/etcdtls/member/server-tls/server.crt
    - --key-file=/etc/etcdtls/member/server-tls/server.key
    - --initial-cluster-token=9ee644c6-1f6f-4c55-ac6b-6230bc65aef2
```

**Liveness and Readiness checks:**

```
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl --endpoints=https://localhost:2379 --cert=/etc/etcdtls/operator/etcd-tls/etcd-client.crt
          --key=/etc/etcdtls/operator/etcd-tls/etcd-client.key --cacert=/etc/etcdtls/operator/etcd-tls/etcd-client-ca.crt
          endpoint status
```

**workaround:**

replace `--endpoints=https://localhost:2379` to `--endpoints=https://localhost:2379,https://localhost:2379`

server cert:

```
## SAN

*.cilium-etcd-cluster-.kube-system.svc
cilium-etcd-cluster-client.kube-system.svc
*.mesh.cilium.io
localhost

## Usage

Server Authentication
Client Authentication
```

peer cert:

```
## SAN

*.cilium-etcd-cluster.kube-system.svc

## Usage

Server Authentication
Client Authentication

```
