### ISSUE TITLE
Etcdctl to use ~/.etcdctl config file, similar to kubectl?

### ISSUE THREAD

**Issue by seeker89** [etcd-io/etcd#12712]
Hi everyone!

I've been using etcdctl a lot lately, and I found it pretty annoying that it doesn't support something like `~/.etcdctl` config file to specify the locations of certificates, endpoints etc. I typically end up writing a wrapper script specifying the env variables.

Would you be open to a PR contributing support for config files like that? The env vars would still take precedence, if present, but you could specify various context you work with in the config file?

I was thinking something along the lines of how `kubectl` works:

```yaml
$ cat ~/.etcdctl
# this holds an array of configs
contexts:
  - name: sandbox
     config:
       endpoints: ["https://some-node:1234", ...]
       # certs can be specified as a path or a string
       clientCA:
         path: "/somewhere"
       clientCert:
         base64: ......
...
  - name: some-other-cluster
     config:
...
# current context could be stored directly in the file
config:
    current-context: sandbox
```

And then I could do something like `etcdctl --context some-other-cluster endpoint health`.

Or `etcdctl config set-context sandbox` and then `etcdctl endpoints health`, just like you'd do with `kubectl`.

What do you think?
