### ISSUE TITLE
KeyFile and CertFile are not presented

### ISSUE THREAD

**Issue by gpettey** [etcd-io/etcd#12887]
etcd Version: 3.4.15
Git SHA: aa7126864
Go Version: go1.12.17
Go OS/Arch: linux/amd64

$ ./etcd --config-file /opt/etcd/etcd.conf
... snip ...
2021-04-22 12:57:24.547438 C | etcdmain: cannot listen on TLS for 10.0.0.51:2380: KeyFile and CertFile are not presented

$ grep -C1 'cert\\\|key' etcd.conf
```yaml
client-transport-security:
  cert-file: /path/to/key.pem
  key-file: /path/to/cert.pem
peer-transport-security:
  peer-cert-file: /path/to/key.pem
  peer-key-file: /path/to/cert.pem
```

The same cert and key function properly when config is all supplied by CLI option or environment instead of the conf file.
