### ISSUE TITLE
New members showing "unstarted" in member list

### ISSUE THREAD

**Issue by pgodfrin-nov** [etcd-io/etcd#13153]
I'm building a new cluster, but I'm stymied at two. I bootstrapped one (tstsdb21), it shows started. Then on the other machine I bootstrap the other one (tstsdb22). Also added the members, here's what shows up
```
postgres@tstsdb21:~=> eee mem list
+------------------+-----------+---------------+--------------------------+----------------------+------------+
|        ID        |  STATUS   |     NAME      |        PEER ADDRS        |     CLIENT ADDRS     | IS LEARNER |
+------------------+-----------+---------------+--------------------------+----------------------+------------+
| 180dd7e4aa0e5241 |   started | etcd-tstsdb21 | http://172.31.3.183:2380 | http://tstsdb21:2379 |      false |
| 9829801ef17d0972 | unstarted |               | http://172.31.1.102:2380 |                      |      false |
+------------------+-----------+---------------+--------------------------+----------------------+------------+
```
On the other machine:
```
postgres@tstsdb22:/postgres/admin/etcd=> eee mem list
+------------------+-----------+---------------+--------------------------+----------------------+------------+
|        ID        |  STATUS   |     NAME      |        PEER ADDRS        |     CLIENT ADDRS     | IS LEARNER |
+------------------+-----------+---------------+--------------------------+----------------------+------------+
| 180dd7e4aa0e5241 |   started | etcd-tstsdb21 | http://172.31.3.183:2380 | http://tstsdb21:2379 |      false |
| 9829801ef17d0972 | unstarted |               | http://172.31.1.102:2380 |                      |      false |
+------------------+-----------+---------------+--------------------------+----------------------+------------+
```

The logs show these messages (sdb21):
```
2021-06-28 18:23:02.379159 E | rafthttp: request sent was ignored (cluster ID mismatch: remote[9829801ef17d0972]=98262bf4a26de695, local=a28f361743166b6f)
```
and on sdb22:
```
2021-06-28 18:23:33.851009 E | rafthttp: request sent was ignored (cluster ID mismatch: remote[31fa18b5951d00e0]=a28f361743166b6f, local=98262bf4a26de695)
```

Here's a condensed version of my config files:
```
postgres@tstsdb22:/postgres/admin/etcd=> cat tstsdb22-etcd.yaml 
name: 'etcd-tstsdb22'
data-dir: '/dcs/etcd/data'
snapshot-count: 10000
heartbeat-interval: 100
election-timeout: 1000
quota-backend-bytes: 0
listen-peer-urls: http://172.31.1.102:2380
listen-client-urls: http://172.31.1.102:2379
max-snapshots: 5
max-wals: 5
cors:
initial-advertise-peer-urls: http://tstsdb22:2380
advertise-client-urls: http://tstsdb22:2379
discovery:
discovery-fallback: 'proxy'
discovery-proxy:
discovery-srv:
initial-cluster:  "etcd-tstsdb21=http://172.31.3.183:2380,etcd-tstsdb22=http://172.31.1.102:2380"
initial-cluster-token: 'etcd-tstsdb22'
initial-cluster-state: 'existing'
strict-reconfig-check: false
enable-v2: false
enable-pprof: true
proxy: 'off'
proxy-failure-wait: 5000
proxy-refresh-interval: 30000
proxy-dial-timeout: 1000
proxy-write-timeout: 5000
proxy-read-timeout: 0
client-transport-security:
  cert-file:
  key-file:
  client-cert-auth: false
  trusted-ca-file:
  auto-tls: false
peer-transport-security:
  cert-file:
  key-file:
  client-cert-auth: false
  trusted-ca-file:
  auto-tls: false
log-level: error
logger: zap
log-outputs: [stderr]
force-new-cluster: false
auto-compaction-mode: periodic
auto-compaction-retention: "1"
enable-grpc-gateway: true
```
(it's the same for sdb21...)

What on earth am I missing??
