### ISSUE TITLE
Provide a better liveness probe for when etcd runs as a Kubernetes pod

### ISSUE THREAD

**Issue by randomvariable** [etcd-io/etcd#13340]
In Kubernetes clusters provisioned by [kubeadm](https://kubernetes.io/docs/reference/setup-tools/kubeadm/) and [Kubernetes Cluster API](https://github.com/kubernetes-sigs/cluster-api), etcd is colocated with API server and is run as a Kubernetes static pod.

The following liveness probe is used:

```yaml
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
```

As per https://github.com/kubernetes/kubernetes/issues/96886, the /health endpoint returns unhealthy under the following conditions:

* there is an active Alarm (there are two kinds of alarm: NOSPACE and CORRUPT)
* there is no raft leader
* the latency of a QGET request doesn't exceed 1s

However, in most of these cases we don't want etcd restarted

* there is no raft leader: This most commonly occurs when the entire cluster is switched off and at a later point turned back on. There is no raft leader, but kubelet repeatedly restarts the etcd pods before a leader election can take place.
* the latency of a QGET request doesn't exceed 1s: This can happen for a number of reasons, but a restart is unlikely to solve the issue.

In contrast to the statements in https://github.com/kubernetes/kubernetes/issues/96886, it may be suitable to restart the pod when the NOSPACE alarm is reached since another process in the background may increase the volume size and allow the pod to start - but this is dependent on the underlying orchestration.

In https://github.com/kubernetes/kubernetes/pull/97034, Kubernetes e2e tests were changed executing etcdctl with the healthcheck endpoint with a quorum read. However, even in the case of a whole cluster restart, then we still do not want etcd pods restarted if a quorum read isn't possible as followers may be in the process of catching up.

Essentially, the Kubernetes liveness probe should be based on availability rather than integrity, and higher level systems such as Kubernetes Cluster API can remediate problems with integrity through further introspection.

Technically, we could change the livenessProbe to use `etcdctl` and run our own test, e.g.:

```
ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key get --consistency="s" foo
```

will do a local read and return 0 if successful.

However, since there is an intention to remove the client binaries from the default etcd image, we would not want to rely on it, and kubeadm was explicitly changed to only use `/health` (see https://github.com/kubernetes/kubeadm/issues/1708). 

I think there are two options here:

1. Provide a "lightweight" /ready endpoint 
  - Both an advantage or disadvantage of this is that it'll be opinionated
  - Different cluster operators may have different understandings of "OK". e.g. whether or not the pod should be restarted based on a NOSPACE alarm.
2. Add more query parameters to `/health` and allow consumers to decide what they want
  - The `/health` endpoint already supports excluding certain alarms using the `exclude` parameter.
  - We could add `NORAFTLEADER` to the list of possible exclusions
  - We could additionally add support for setting the consistency level of the test read.
  - e.g. `/health?exclude=NORAFTLEADER&consistency=s`

I think doing option 2 also encompasses in a more generic fashion some of the changes in https://github.com/etcd-io/etcd/pull/13317, since in learner mode we also only want a serializable read.
