### ISSUE TITLE
Kubelet liveness probe restarts etcd when auth is enabled

### ISSUE THREAD

**Issue by bsctl** [etcd-io/etcd#13415]
# Issue description
We have an HA etcd cluster as external data store for kubernetes, according to [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/) and [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/#external-etcd-topology).

Enabling the authentication, the `kubelet` restarts the `etcd` instances  because  liveness probe on `http://127.0.0.1/health` fails due to missing authentication.

```bash
etcdctl user add root
etcdctl role add root
etcdctl user grant-role root root
etcdctl auth enable
```

```
sudo crictl ps -a
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID
0dc22b980250c       0048118155842       43 seconds ago      Running             etcd                2                   ec877edb48950
0be9dfd049fcf       0048118155842       4 minutes ago       Exited              etcd                1                   ec877edb48950
```

```
sudo crictl logs 0be9dfd049fcf
...
{"level":"warn","ts":"2021-10-13T08:43:56.974Z","caller":"etcdhttp/metrics.go:78","msg":"/health error","output":"{\"health\":\"false\",\"reason\":\"RANGE ERROR:auth: user name is empty\"}","status-code":503}
```

Here the etcd manifest

```yaml
$ sudo cat /etc/kubernetes/manifests/etcd.yaml 
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/etcd.advertise-client-urls: https://10.9.6.173:2379
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://10.9.141.173:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=https://10.9.141.173:2380
    - --initial-cluster=etcd01=https://10.9.141.173:2380,etcd02=https://10.9.141.174:2380,etcd03=https://10.9.141.175:2380
    - --initial-cluster-state=new
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://10.9.141.173:2379
    - --listen-metrics-urls=http://127.0.0.1:2381
    - --listen-peer-urls=https://10.9.141.173:2380
    - --name=etcd01
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: k8s.gcr.io/etcd:3.5.0-0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: etcd
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    startupProbe:
      failureThreshold: 25
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}
```

I'm not sure requiring authentication on `/health` path is necessary since it is just readonly.

# Versions
```
etcd version: 3.5.0
API version: 3.5
kubelet 1.22.2
```
