### ISSUE TITLE
Unable to specify time.Duration types in etcd config file 

### ISSUE THREAD

**Issue by Oats87** [etcd-io/etcd#13480]
While performing testing with `etcd`, I found I am unable to set `time.Duration` types if configuring etcd via config file.

This is with a configuration file that is like:
```
advertise-client-urls: https://172.16.135.67:2379
client-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
data-dir: /var/lib/rancher/k3s/server/db/etcd
election-timeout: 5000
heartbeat-interval: 500
listen-client-urls: https://172.16.135.67:2379,https://127.0.0.1:2379
listen-metrics-urls: http://127.0.0.1:2381
listen-peer-urls: https://172.16.135.67:2380
log-outputs:
- stderr
logger: zap
name: ck-c7-1-cbad9bf0
peer-transport-security:
  cert-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt
  client-cert-auth: true
  key-file: /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key
  trusted-ca-file: /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt
grpc-keepalive-timeout: 40s
```

I get an error like:
```
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field configYAML.grpc-keepalive-timeout of type time.Duration
```

I'm not really sure if there is a better documented way to do this but my understanding was that I should be able to specify parameters via config file that are identical to the way I would specify them on the command-line, which is what I'm doing.
