### ISSUE TITLE
Enhance the static-analysis workflow

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#14164]
Some issues were found using [revive](https://github.com/mgechev/revive), such as,
* https://github.com/etcd-io/etcd/issues/14162
* https://github.com/etcd-io/etcd/pull/14160
* https://github.com/etcd-io/etcd/pull/14163

We should enhance the [static-analysis](https://github.com/etcd-io/etcd/blob/main/.github/workflows/static-analysis.yaml) workflow. The [revive](https://github.com/mgechev/revive) has already been integrated into [golangci-lint](https://github.com/golangci/golangci-lint). So I think we can enhance the static-analysis using the `golangci-lint `?

cc @serathius @ptabor @spzala @chavacava @ldez @jirfag @ernado

**Comment by chavacava** [comment]
`revive` has more than 65 rules and, of course, there is some overlap with those of the other linters `golangci-lint` can run.

When looking for potential bugs I use the following `revive` configuration: 
```toml
ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 0

[rule.constant-logical-expr]
[rule.time-equal]
[rule.unreachable-code]
[rule.struct-tag]
[rule.modifies-value-receiver]
[rule.bool-literal-in-expr]
[rule.range-val-in-closure]
[rule.range-val-address]
[rule.datarace]
[rule.string-of-int]
[rule.unconditional-recursion]
[rule.identical-branches]
```

**Comment by cenkalti** [comment]
I am willing to work on this task is no one else has started yet. I can integrate `golangci-lint`. After integration is done we can talk about which linter to turn on/off and rules.

**Comment by ramses** [comment]
Yesterday I finished exactly this for another project — i.e., golangci-lint for the project, then added a github action.

I've just noticed that we do not have the following:

- `.golangci.yml` configuration.
- `make` target for linting  — this and the above bullet would enable repeatable local linting.

Also, the static analysis workflow calls the `scripts/test.sh`. Instead, we could use the `golangci-lint` github-action for static analysis.

Thoughts?

**Comment by cenkalti** [comment]
It's better to use Github actions instead of writing more script code.

**Comment by ramses** [comment]
> It's better to use Github actions instead of writing more script code.

I'm not recommending more script code.

I am recommending LESS script code.

A configuration file for `golangci-lint` would enable local tests.

Using the golangci-lint-github-action would simplify `scripts/test.sh`.

Your thoughts?

**Comment by cenkalti** [comment]
Agreed. That's what I was trying to say.

**Comment by ahrtr** [comment]
Thanks both @cenkalti and @ramses for the feedback. Actually I tried the `golangci-lint` as well about 9 months ago in project [gocontainer](https://github.com/ahrtr/gocontainer), and I believe it's definitely useful, but we also need to avoid some false alarms. 

@serathius @spzala @ptabor  do you have any immediate concern on this approach? If no any objection, @cenkalti and @ramses , please any of you feel free to deliver a PR on this.

**Comment by ernado** [comment]
Don't be shy to ignore false positives. Here is example from one of my projects:

```yml
issues:
  exclude-use-default: false
  exclude-rules:
    # TODO(ernado): Should we refactor Parse() functions?
    - path: exchange
      linters: [ gocyclo, gocognit ]
      text: "Run"

    - linters: [ gocritic ]
      text: "commentedOutCode"
      source: "SHA1"

    # Exclude go:generate from lll
    - source: "//go:generate"
      linters: [ lll ]

    # Disable linters that are annoying in tests.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - scopelint
        - lll

    # Ignore shadowing of err.
    - linters: [ govet ]
      text: 'declaration of "(err|ctx|log)"'

    # Ignore linters in main packages.
    - path: cmd\/.+\/main\.go
      linters: [ goconst, funlen, gocognit, gocyclo ]

    # Intended in commands:
    # G307: Deferring unsafe method "Close" on type "*os.File"
    # G304: Potential file inclusion via variable
    - path: cmd\/.+\/main\.go
      text: G(307|304)

    - linters: [ goconst ]
      text: 'string `(bool|int64)`'

    - path: tgtest
      linters: [ revive, golint ]
      text: "should have comment or be unexported"

    - linters: [ staticcheck ]
      text: "SA1019: telegram.+ is deprecated:"

    - linters: [ staticcheck ]
      text: 'SA1019: strings\.Title has been deprecated'

    - linters: [ revive ]
      text: "if-return: redundant if ...; err != nil check, just return error instead."

    - linters: [ unparam ]
      text: "Builder.+is never used"
```

The `exclude-rules` section is very flexible and it is ok to disable some checks fully or partially.
