### ISSUE TITLE
failed to find [SNAPSHOT-INDEX].snap.db (ALARM NOSPACE + kubeadm liveness probe for etcd -> crashloop?)

### ISSUE THREAD

**Issue by wjentner** [etcd-io/etcd#14497]
### What happened?

Our etcd is deployed on separate nodes (VMs) and provisioned by kubeadm.

At some point we ran into the ALARM NO SPACE failure since our DB SIZE reached 2.2 GB.
Kubeadm starts the etcd pods with a liveness probe to `/health`. When the alarm occurs, the health status is != 200 and the etcd pod goes into CrashLoopBackoff. I guess within that crash loop etcd failed completely so that it was unable to recover by itself.

I could recover etcd by using the `snap/db` (as described in the disaster recovery doc).

For now, I have increaesed the --quota-backend-bytes to 8GB and also enabled auto compaction to not run again into the alarm.

### What did you expect to happen?

I think this is an unfortunate combination of events.
Perhaps another warning alert should be raised before no space such that admins can react.
Also, it would be nice if the alerts would be propagated to the /metrics endpoint, this would have helped us to see the problem early on.

### How can we reproduce it (as minimally and precisely as possible)?

kubeadm provisions etcd as a static pod:

```yaml
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/etcd.advertise-client-urls: https://xxx.xxx.224.162:2379
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://xxx.xxx.224.162:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --experimental-initial-corrupt-check=true
    - --initial-advertise-peer-urls=https://xxx.xxx.224.162:2380
    - --initial-cluster=kube-etcd1=https://xxx.xxx.224.162:2380,kube-etcd2=https://xxx.xxx.224.163:2380,kube-etcd5=https://xxx.xxx.224.238:2380
    - --initial-cluster-state=existing
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://xxx.xxx.224.162:2379
    - --listen-metrics-urls=http://127.0.0.1:2381
    - --listen-peer-urls=https://xxx.xxx.224.162:2380
    - --name=kube-etcd1
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    # follow the docs: https://etcd.io/docs/v3.5/op-guide/maintenance/#space-quota
    - --quota-backend-bytes=16777216
    image: k8s.gcr.io/etcd:3.5.1-0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 80
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: etcd
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    startupProbe:
      failureThreshold: 240
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
```

Then follow the docs here: https://etcd.io/docs/v3.5/op-guide/maintenance/#space-quota
until the alarm is raised.
You should start seeing that the pod is now in CrashLoopBackoff.

### Anything else we need to know?

The same error happened on all etcd nodes, just the snaphot index was different:
```
etcd1: {"level":"warn","ts":"2022-09-16T17:53:40.235Z","caller":"snap/db.go:88","msg":"failed to find [SNAPSHOT-INDEX].snap.db","snapshot-index":893213589,"snapshot-file-path":"/var/lib/etcd/member/snap/00000000353d5b95.snap.db","error":"snap: snapshot file doesn't exist"}
etcd2: {"level":"warn","ts":"2022-09-16T17:47:06.327Z","caller":"snap/db.go:88","msg":"failed to find [SNAPSHOT-INDEX].snap.db","snapshot-index":893216556,"snapshot-file-path":"/var/lib/etcd/member/snap/00000000353d672c.snap.db","error":"snap: snapshot file doesn't exist"}
etcd5: {"level":"warn","ts":"2022-09-16T17:46:30.424Z","caller":"snap/db.go:88","msg":"failed to find [SNAPSHOT-INDEX].snap.db","snapshot-index":893201552,"snapshot-file-path":"/var/lib/etcd/member/snap/00000000353d2c90.snap.db","error":"snap: snapshot file doesn't exist"}
```

### Etcd version (please run commands below)

<details>

**Note, at the time of crash it was etcd version 3.5.1.**

```console
$ etcd --version
# paste output here
etcd Version: 3.5.5
Git SHA: 19002cfc6
Go Version: go1.16.15
Go OS/Arch: linux/amd64


$ etcdctl version
# paste output here
etcdctl version: 3.5.5
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

```yaml
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/etcd.advertise-client-urls: https://xxx.xxx.224.162:2379
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://xxx.xxx.224.162:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --experimental-initial-corrupt-check=true
    - --initial-advertise-peer-urls=https://xxx.xxx.224.162:2380
    - --initial-cluster=kube-etcd1=https://xxx.xxx.224.162:2380,kube-etcd2=https://xxx.xxx.224.163:2380,kube-etcd5=https://xxx.xxx.224.238:2380
    - --initial-cluster-state=existing
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://xxx.xxx.224.162:2379
    - --listen-metrics-urls=http://127.0.0.1:2381
    - --listen-peer-urls=https://xxx.xxx.224.162:2380
    - --name=kube-etcd1
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    # follow the docs: https://etcd.io/docs/v3.5/op-guide/maintenance/#space-quota
    - --quota-backend-bytes=16777216
    image: k8s.gcr.io/etcd:3.5.1-0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 80
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: etcd
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    startupProbe:
      failureThreshold: 240
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
```

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```shell
{"level":"info","ts":"2022-09-16T18:51:16.637Z","caller":"etcdmain/etcd.go:73","msg":"Running: ","args":["etcd","--advertise-client-urls=https://xxx.xxx.224.162:2379","--ce
rt-file=/etc/kubernetes/pki/etcd/server.crt","--client-cert-auth=true","--data-dir=/var/lib/etcd","--experimental-initial-corrupt-check=true","--initial-advertise-peer-url
s=https://xxx.xxx.224.162:2380","--initial-cluster=etcd1=https://xxx.xxx.224.162:2380","--initial-cluster-state=existing","--key-file=/etc/kubernetes/pki/etcd/server.key","-
-listen-client-urls=https://xxx.xxx.224.162:2379","--listen-metrics-urls=http://127.0.0.1:2381","--listen-peer-urls=https://xxx.xxx.224.162:2380","--name=etcd1","--peer-cert
-file=/etc/kubernetes/pki/etcd/peer.crt","--peer-client-cert-auth=true","--peer-key-file=/etc/kubernetes/pki/etcd/peer.key","--peer-trusted-ca-file=/etc/kubernetes/pki/etc
d/ca.crt","--snapshot-count=10000","--trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt"]}
{"level":"info","ts":"2022-09-16T18:51:16.637Z","caller":"etcdmain/etcd.go:116","msg":"server has been already initialized","data-dir":"/var/lib/etcd","dir-type":"member"}
{"level":"info","ts":"2022-09-16T18:51:16.637Z","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":["https://xxx.xxx.224.162:2380"]}
{"level":"info","ts":"2022-09-16T18:51:16.637Z","caller":"embed/etcd.go:479","msg":"starting with peer TLS","tls-info":"cert = /etc/kubernetes/pki/etcd/peer.crt, key = /et
c/kubernetes/pki/etcd/peer.key, client-cert=, client-key=, trusted-ca = /etc/kubernetes/pki/etcd/ca.crt, client-cert-auth = true, crl-file = ","cipher-suites":[]}
{"level":"info","ts":"2022-09-16T18:51:16.638Z","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-urls":["https://xxx.xxx.224.162:2379"]}
{"level":"info","ts":"2022-09-16T18:51:16.638Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.3","git-sha":"0452feec7","go-version":"go1
.16.15","go-os":"linux","go-arch":"amd64","max-cpu-set":8,"max-cpu-available":8,"member-initialized":true,"name":"etcd1","data-dir":"/var/lib/etcd","wal-dir":"","wal-dir-d
edicated":"","member-dir":"/var/lib/etcd/member","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","initial-election-tick-advance":true,"snaps
hot-count":10000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["https://xxx.xxx.224.162:2380"],"listen-peer-urls":["https://xxx.xxx.224.162:2380"],"advertis
e-client-urls":["https://xxx.xxx.224.162:2379"],"listen-client-urls":["https://xxx.xxx.224.162:2379"],"listen-metrics-urls":["http://127.0.0.1:2381"],"cors":["*"],"host-whit
elist":["*"],"initial-cluster":"","initial-cluster-state":"existing","initial-cluster-token":"","quota-size-bytes":2147483648,"pre-vote":true,"initial-corrupt-check":true,
"corrupt-check-time-interval":"0s","auto-compaction-mode":"periodic","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":
"","downgrade-check-interval":"5s"}
{"level":"info","ts":"2022-09-16T18:51:22.364Z","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/var/lib/etcd/member/snap/db","took":"5.724926509s"}
{"level":"info","ts":"2022-09-16T18:51:23.172Z","caller":"etcdserver/server.go:508","msg":"recovered v2 store from snapshot","snapshot-index":893213589,"snapshot-size":"10
5 kB"}
{"level":"warn","ts":"2022-09-16T18:51:23.259Z","caller":"snap/db.go:88","msg":"failed to find [SNAPSHOT-INDEX].snap.db","snapshot-index":893213589,"snapshot-file-path":"/
var/lib/etcd/member/snap/00000000353d5b95.snap.db","error":"snap: snapshot file doesn't exist"}
{"level":"panic","ts":"2022-09-16T18:51:23.260Z","caller":"etcdserver/server.go:515","msg":"failed to recover v3 backend from snapshot","error":"failed to find database sn
apshot file (snap: snapshot file doesn't exist)","stacktrace":"go.etcd.io/etcd/server/v3/etcdserver.NewServer\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdserver/ser
ver.go:515\ngo.etcd.io/etcd/server/v3/embed.StartEtcd\n\t/go/src/go.etcd.io/etcd/release/etcd/server/embed/etcd.go:245\ngo.etcd.io/etcd/server/v3/etcdmain.startEtcd\n\t/go
/src/go.etcd.io/etcd/release/etcd/server/etcdmain/etcd.go:228\ngo.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdmai
n/etcd.go:123\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/main.go:40\nmain.main\n\t/go/src/go.etcd.io/etcd/release/etc
d/server/main.go:32\nruntime.main\n\t/go/gos/go1.16.15/src/runtime/proc.go:225"}
panic: failed to recover v3 backend from snapshot
```
