### ISSUE TITLE
Enable Dependabot for etcd if we see a good fit

### ISSUE THREAD

**Issue by vivekpatani** [etcd-io/etcd#14673]
### What would you like to be added?

[Dependabot](https://github.com/dependabot)

Should we introduce this tool?

### Why is this needed?

Pros:
1. Notifies of newer library versions (https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) - by notifications or creates an automated PR. This helps us is keeping up with the latest versions, which in some degree may bring in bug fixes/security updates/improvements/etc.
2. Notifies of insecure library versions (https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts) - helps us with detecting if there are any security issues with any of our libraries.

Cons:
1. More noise from the bot (depends on how we configure it)
2. Can sometimes fix problems, which may be a `good-first-issue` for some folks trying to engage with the open source community.

Please feel free to feedback, this is just a suggestion. Thanks.

**Comment by serathius** [comment]
I'm all for it.

> More noise from the bot (depends on how we configure it)

We just want to get a PR once a week that updates dependencies in go.mod. Doesn't seem like to much noise.

> Can sometimes fix problems, which may be a good-first-issue for some folks trying to engage with the open source community. 

Don't think pushing toil like updating dependencies is a good first contributor experience.

**Comment by vivekpatani** [comment]
@ahrtr @spzala @mitake @ptabor any thoughts?

**Comment by ahrtr** [comment]
I don't have strong opinion on this, but I think it's worth a try.

**Comment by vivekpatani** [comment]
@serathius would you or one of the maintainers enable this? Seems like I'm not authorised to do this.

**Comment by serathius** [comment]
@vivekpatani Dependabot is enabled by adding a configuration to repository. Anyone can create a PR that adds it. Benefit of maintainers is that they can do that directly on main branch, which doesn't make sense as it voids code review.

Feel free to send the PR that adds the configuration, you just need to add a `.github/dependabot.yml` file. Default contents that might need some adjustments 
```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```
