### ISSUE TITLE
Specify branch name for the "Trivy Nightly Scan"

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#15009]
### What would you like to be added?

Recently we added "Trivy Nightly Scan" for both release-3.5 and release-3.4, but we do not specify the branch name.  Based on the [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule), it's the last commit of the default branch, which is the `main` branch. 

We need to specify the correct branch name. Specifically, we need to specify release-3.5 for [3.5 trivy-nightly-scan.yaml](https://github.com/etcd-io/etcd/blob/release-3.5/.github/workflows/trivy-nightly-scan.yaml), and specify release-3.4 for [3.4 trivy-nightly-scan.yaml](https://github.com/etcd-io/etcd/blob/release-3.4/.github/workflows/trivy-nightly-scan.yaml)

```
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          ref: release-3.5
```

```
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          ref: release-3.4
```

### Why is this needed?

Context: https://github.com/etcd-io/etcd/issues/15003
