### ISSUE TITLE
Grant kick off / restart github actions workflow permissions to members

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#15659]
### What would you like to be added?

Follow up to https://github.com/etcd-io/etcd/pull/15593#discussion_r1153745892

Need to figure out how to do that, one way would be to adopt K8s bot but that comes with it's own downsides.

### Why is this needed?

Would be great reward

**Comment by gusmith-ambiata** [comment]
Hi @chaochn47 , I've been pinged in the discussion you mentioned.
Sorry I cannot share the project I'm working on which is private.
But what we did was to use a workflow issue trigger, i.e. our workflow gets triggered on issue creation. We decided to use filter on the issue name to know if the workflow should actually do something, e.g. if the newly created issue's name starts with `[#run-my-workflow]` then the workflow's first step is to assess if it should actually run. The following steps are conditional based on the output of the first step.
Then, to give feedback to the users, I'm using `gh` for example `gh issue comment ${ISSUE_NUMBER} --body "I will be your bot for today."` 
Not necessarily working example (poorly copied/pasted removing a lot of things to be able to share it) :
```
name: "Workflow triggered by issue creation/re-opening"
on:
  issues:
    types: [opened, reopened]

env:
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  CURRENT_BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  my-job:
    if: ${{ !github.event.issue.pull_request }} # I don't want it triggered on PRs
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bot present itself
      run: |
            gh issue comment ${ISSUE_NUMBER} --body "I will be your scanner bot for today, here is your [build url](${CURRENT_BUILD_URL})."
    - name: Select if continue
      id: continue_selector
      env:
        TITLE: ${{ github.event.issue.title }}
      run: |
        if [[ ${TITLE} =~ "^[#run-my-workflow](.*)$" ]]; then
          echo "We will continue the workflow"
          echo "continue=true" >> ${GITHUB_OUTPUT}
        else
          echo "We will not continue the workflow"
          echo "continue=false" >> ${GITHUB_OUTPUT}
        fi
    - name: If to continue
      if: ${{ steps.continue_selector.outputs.continue }}
      run: |
         gh issue comment ${ISSUE_NUMBER} --body "Yeah, I have to run"
```

So in a nutshell, this workflow is triggered everytime an issue is created, but some steps are ran only if it should based on a condition on the issue name.
