### ISSUE TITLE
Performance Issue : Getting error etcdserver: too many requests during high load

### ISSUE THREAD

**Issue by BharathMC** [etcd-io/etcd#16287]
### Bug report criteria

- [X] This bug report is not security related, security issues should be disclosed privately via security@etcd.io.
- [X] This is not a support request, support requests should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [X] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [X] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

Hi Team, 

We are using etcd as a KV store for our project and during performance testing, we are observed that etcd is rejecting the requests with error `"etcdserver: too many requests"`.

**Our use case involves 14 etcd interactions for single transaction:**
- Reads : 8 times
- Writes : 5 times
- Final write : 1 time 
- During `final write`, we create a `lease` with TTL 60s and attach the lease to the key. So once the TTL reach, the key gets deleted.

With this, we are able to get about 950 to 1000 Transactions per second. But after sometime of the performance test, etcd server is rejecting the requests with `"etcdserver: too many requests"`

### Etcd logs can be found here:
[etcd-pods-combined-1.log.zip](https://github.com/etcd-io/etcd/files/12146249/etcd-pods-combined-1.log.zip)

**Additional logs:**
[etcd-pods-combined-2.log.zip](https://github.com/etcd-io/etcd/files/12146266/etcd-pods-combined-2.log.zip)
[etcd-pods-combined-3.log.zip](https://github.com/etcd-io/etcd/files/12146270/etcd-pods-combined-3.log.zip)

### Heap dump analysis:
[HeapDump.zip](https://github.com/etcd-io/etcd/files/12146274/HeapDump.zip)

### What did you expect to happen?

With the dedicated high end baremetal machines using NVMe SSD Storage, the throughput seems to be fine. But when there are huge number of requests, etcd is not scaling. 

### How can we reproduce it (as minimally and precisely as possible)?

We may need to create an method with similar etcd interactions mentioned below and expose it to REST API. And use JMeter or any preferable load test tool and call the API with approximately 2k threads in loop and hold it for 2 hours. `etcdserver: too many requests` will be reproducible after 90 minutes.

```
Our use case involves 14 etcd interactions for single transaction:
- Reads : 8 times
- Writes : 5 times
- Final write : 1 time 
- During `final write`, we create a `lease` with TTL 60s and attach the lease to the key. So once the TTL reach, the key gets deleted.
```

If required, I can build one sample application and share the source of it.

### Some metrics for analysis

**Metrics:** `grpc_server_started_total `
When the failure happened, it was about 5300 RPS.

<img width="1360" alt="Screenshot 2023-07-24 at 1 30 16 AM" src="https://github.com/etcd-io/etcd/assets/7956530/076daf69-d3e9-41b1-89a9-9dbc38f80937">

---------------------------------------------------------------------------------------------------------------------

### Database Size:
**Metrics:**  
`etcd_mvcc_db_total_size_in_bytes`
`etcd_mvcc_db_total_size_in_use_in_bytes`

<img width="907" alt="Screenshot 2023-07-24 at 1 30 37 AM" src="https://github.com/etcd-io/etcd/assets/7956530/af844f89-99de-414f-aef1-24d514fe30ed">

DBSize: (etcd_mvcc_db_total_size_in_bytes): database size including free space waiting for defragmentation
DBSizeInUse(etcd_mvcc_db_total_size_in_use_in_bytes): actual database usage

---------------------------------------------------------------------------------------------------------------------
### Lease stats:
**Metrics:**  
`etcd_debugging_lease_granted_total`
`etcd_lease_object_counts_count`
`etcd_debugging_lease_revoked_total`
`etcd_debugging_lease_ttl_total_count`
`etcd_debugging_lease_ttl_total_sum`

<img width="1358" alt="Screenshot 2023-07-24 at 1 30 57 AM" src="https://github.com/etcd-io/etcd/assets/7956530/bc5a38fb-f00d-4545-a8d9-329da20ca506">

---------------------------------------------------------------------------------------------------------------------
### Proposals Pending:
**Metrics:** `etcd_server_proposals_pending`

<img width="680" alt="Screenshot 2023-07-24 at 1 31 31 AM" src="https://github.com/etcd-io/etcd/assets/7956530/17d45004-3d43-4682-bc28-597f71e60764">

---------------------------------------------------------------------------------------------------------------------
### Slow Operations:
**Metrics:** 
`etcd_server_slow_apply_total`
`etcd_server_slow_read_indexes_total`

<img width="678" alt="Screenshot 2023-07-24 at 6 22 35 PM" src="https://github.com/etcd-io/etcd/assets/7956530/69485b71-e612-451b-b1a7-c1a3200480f4">

---------------------------------------------------------------------------------------------------------------------
### CPU usage by pod (Only one pod is scheduled to each node )

<img width="1359" alt="Screenshot 2023-07-24 at 1 31 58 AM" src="https://github.com/etcd-io/etcd/assets/7956530/046c9b1f-117b-480d-b5b0-4e3e5903b7a4">
---------------------------------------------------------------------------------------------------------------------
### Memory usage by etcd pod
<img width="1356" alt="Screenshot 2023-07-24 at 1 32 08 AM" src="https://github.com/etcd-io/etcd/assets/7956530/0561ffcd-0e32-458b-bc10-ba525eaeb4cc">

---------------------------------------------------------------------------------------------------------------------
### Keys compacted 
**Metrics:** 
`etcd_debugging_mvcc_keys_total`
`etcd_debugging_mvcc_db_compaction_keys_total`

<img width="1352" alt="Screenshot 2023-07-24 at 1 33 07 AM" src="https://github.com/etcd-io/etcd/assets/7956530/cbaa1f25-ab61-4a34-a216-97e40ea7200a">

---------------------------------------------------------------------------------------------------------------------
### Disk Synchronization
**Metrics:**  `etcd_disk_wal_fsync_duration_seconds_bucket`
**Query** `histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job="$Namespace"}[5m])) by (instance, le))`

<img width="453" alt="Screenshot 2023-07-24 at 1 33 19 AM" src="https://github.com/etcd-io/etcd/assets/7956530/d9caced5-3bf0-493d-a637-a3f7934d17f4">

---------------------------------------------------------------------------------------------------------------------
### Snapshot Duration
**Metrics:** `etcd_disk_backend_snapshot_duration_seconds_sum`
**Query:** `sum(rate(etcd_disk_backend_snapshot_duration_seconds_sum{job="$Namespace"}[5m]))`
<img width="676" alt="Screenshot 2023-07-24 at 6 28 40 PM" src="https://github.com/etcd-io/etcd/assets/7956530/3d952b6a-679b-4124-a699-f72e9c0df8d3">

---------------------------------------------------------------------------------------------------------------------
### GETs and PUTs
**GET Metrics:** `sum(irate(etcd_mvcc_range_total{job="$Namespace"}[1m]))/60`
**PUT Metrics:** `sum(irate(etcd_mvcc_put_total{job="$Namespace"}[1m]))/60`

<img width="796" alt="Screenshot 2023-07-24 at 6 30 08 PM" src="https://github.com/etcd-io/etcd/assets/7956530/16688e35-a30d-4e00-9cc5-b436ecc864b2">

---------------------------------------------------------------------------------------------------------------------

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
VERSION:
	3.5.5

API VERSION:
	3.5
```
```
$ etcdctl version
etcdctl version: 3.5.5
API version: 3.5
```

</details>

### etcd deployment config for Kubernetes
<details>

```
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-client
spec:
  type: LoadBalancer
  ports:
    - name: etcd-client
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  clusterIP: None
  ports:
    - port: 2379
      name: client
    - port: 2380
      name: peer
  selector:
    app: etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  serviceName: etcd
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      name: etcd
      labels:
        app: etcd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: pooltype
                  operator: In
                  values:
                  - etcdbaremetal
      volumes:
        - name: data
          hostPath:
                    path: /etcdDir/dataDirWithCerts/
                    type: Directory
        - name: config-volume
          configMap:
            name: certs-config-map
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.9-amd64 
          resources:
                limits:
                        memory: "96Gi"
                        cpu: "32"
                requests:
                        memory: "64Gi"
                        cpu: "24"
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          volumeMounts:
            - name: data
              mountPath: /etcdDir/dataDirWithCerts/
            - name: config-volume
              mountPath: /etcdDir/dataDirWithCerts/certs/
          command:
            - etcd
            - --name=$(POD_NAME)
            - --listen-peer-urls http://0.0.0.0:2380 \
            - --listen-client-urls https://0.0.0.0:2379 \
            - --advertise-client-urls https://$(POD_NAME).etcd:2379 \
            - --client-cert-auth \
            - --cert-file=/etcdDir/dataDirWithCerts/certs/server.pem \
            - --key-file=/etcdDir/dataDirWithCerts/certs/server-key.pem \
            - --trusted-ca-file=/etcdDir/dataDirWithCerts/certs/ca.pem \
            - --initial-advertise-peer-urls http://$(POD_NAME):2380 \
            - --initial-cluster-token etcd-cluster-1 \
            - --initial-cluster etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380 \
            - --initial-cluster-state new \
            - --data-dir /etcdDir/dataDirWithCerts/data_dir/default.etcd \
            - --wal-dir /etcdDir/dataDirWithCerts/wal_dir \
            - --quota-backend-bytes=120000000000 \
            - --auto-compaction-retention="1h" \
            - --enable-pprof='true'
---
```

### Hardware for etcd nodes (dedicated only for etcd)
https://docs.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm#bm-hpc-optimized

**BM.Optimized3.36**
Storage: 3.84 TB NVMe SSD
CPU: 36
Memory: 512 GB

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
```
$ etcdctl member list -w table
+------------------+---------+--------+-------------------------+--------------------------+------------+
|        ID        | STATUS  |  NAME  |       PEER ADDRS        |       CLIENT ADDRS       | IS LEARNER |
+------------------+---------+--------+-------------------------+--------------------------+------------+
| 2e80f96756a54ca9 | started | etcd-0 | http://etcd-0.etcd:2380 | https://etcd-0.etcd:2379 |      false |
| 7fd61f3f79d97779 | started | etcd-1 | http://etcd-1.etcd:2380 | https://etcd-1.etcd:2379 |      false |
| b429c86e3cd4e077 | started | etcd-2 | http://etcd-2.etcd:2380 | https://etcd-2.etcd:2379 |      false |
+------------------+---------+--------+-------------------------+--------------------------+------------+
```

$ etcdctl --endpoints=<member list> endpoint status -w table
```
+-----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|          ENDPOINT           |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+-----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://129.80.243.236:2379 | b429c86e3cd4e077 |   3.5.5 |   46 GB |     false |      false |         2 |  152349132 |          152349132 |        |
+-----------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```

</details>


### Relevant log output

```Shell
Pasting some error and failure logs: Complete logs has been attached to this bug

{"level":"info","ts":"2023-07-23T18:54:36.185Z","caller":"traceutil/trace.go:171","msg":"trace[949807065] range","detail":"{range_begin:omtm-xa/otmm-tcs-1235dfc6-9cde-40bd-a372-7b8509c8a022; range_end:; response_count:1; response_revision:77451573; }","duration":"106.984679ms","start":"2023-07-23T18:54:36.078Z","end":"2023-07-23T18:54:36.185Z","steps":["trace[949807065] 'agreement among raft nodes before linearized reading'  (duration: 106.611715ms)"],"step_count":1}
{"level":"info","ts":"2023-07-23T18:54:50.782Z","caller":"fileutil/purge.go:77","msg":"purged","path":"/etcdDir/dataDirWithCerts/data_dir/default.etcd/member/snap/0000000000000002-00000000077366b3.snap"}
{"level":"info","ts":"2023-07-23T18:54:59.532Z","caller":"wal/wal.go:785","msg":"created a new WAL segment","path":"/etcdDir/dataDirWithCerts/wal_dir/000000000000048e-00000000077be4a4.wal"}
{"level":"info","ts":"2023-07-23T18:55:03.351Z","caller":"fileutil/purge.go:77","msg":"purged","path":"/etcdDir/dataDirWithCerts/wal_dir/000000000000048e-00000000075f9c97.wal"}
...
{"level":"info","ts":"2023-07-23T18:55:11.700Z","caller":"etcdserver/server.go:1395","msg":"triggering snapshot","local-member-id":"2e80f96756a54ca9","local-member-applied-index":125603458,"local-member-snapshot-index":125503453,"local-member-snapshot-count":100000}
{"level":"info","ts":"2023-07-23T18:55:11.704Z","caller":"etcdserver/server.go:2405","msg":"saved snapshot","snapshot-index":125603458}
{"level":"info","ts":"2023-07-23T18:55:12.073Z","caller":"etcdserver/server.go:1395","msg":"triggering snapshot","local-member-id":"7fd61f3f79d97779","local-member-applied-index":125605060,"local-member-snapshot-index":125505059,"local-member-snapshot-count":100000}
{"level":"info","ts":"2023-07-23T18:55:12.077Z","caller":"etcdserver/server.go:2405","msg":"saved snapshot","snapshot-index":125605060}
{"level":"info","ts":"2023-07-23T18:55:12.077Z","caller":"etcdserver/server.go:2435","msg":"compacted Raft logs","compact-index":125600060}
{"level":"info","ts":"2023-07-23T18:55:12.737Z","caller":"etcdserver/server.go:1395","msg":"triggering snapshot","local-member-id":"b429c86e3cd4e077","local-member-applied-index":125608841,"local-member-snapshot-index":125508840,"local-member-snapshot-count":100000}
...
{"level":"info","ts":"2023-07-23T19:25:08.896Z","caller":"traceutil/trace.go:171","msg":"trace[2126061347] transaction","detail":"{read_only:false; response_revision:84562285; number_of_response:1; }","duration":"386.758407ms","start":"2023-07-23T19:25:08.509Z","end":"2023-07-23T19:25:08.896Z","steps":["trace[2126061347] 'process raft request'  (duration: 386.208248ms)"],"step_count":1}
{"level":"info","ts":"2023-07-23T19:25:08.923Z","caller":"traceutil/trace.go:171","msg":"trace[610472835] transaction","detail":"{read_only:false; response_revision:84562294; number_of_response:1; }","duration":"412.54692ms","start":"2023-07-23T19:25:08.510Z","end":"2023-07-23T19:25:08.923Z","steps":["trace[610472835] 'process raft request'  (duration: 386.271983ms)","trace[610472835] 'compare'  (duration: 26.059598ms)"],"step_count":2}
{"level":"warn","ts":"2023-07-23T19:25:11.685Z","caller":"etcdserver/server.go:1159","msg":"failed to revoke lease","lease-id":"4ca9895416421b7a","error":"etcdserver: too many requests"}
{"level":"warn","ts":"2023-07-23T19:25:11.685Z","caller":"etcdserver/server.go:1159","msg":"failed to revoke lease","lease-id":"4ca9895416421b7e","error":"etcdserver: too many requests"}
...
{"level":"warn","ts":"2023-07-23T19:25:11.686Z","caller":"etcdserver/server.go:1159","msg":"failed to revoke lease","lease-id":"4ca9895416421fbb","error":"etcdserver: too many requests"}
{"level":"warn","ts":"2023-07-23T19:25:11.686Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"2.763099365s","expected-duration":"100ms","prefix":"","request":"header:<ID:16174547580948784588 username:\"client\" auth_revision:1 > txn:<compare:<key:\"omtm-xa/otmm-tcs-d2af730e-72c5-4081-8adb-e0d0d3f51e6c\" version:4 > success:<request_put:<key:\"omtm-xa/otmm-tcs-d2af730e-72c5-4081-8adb-e0d0d3f51e6c\" value_size:716 lease:6951175544094008613 >> failure:<>>","response":"size:20"}
...
{"level":"info","ts":"2023-07-23T19:25:11.693Z","caller":"traceutil/trace.go:171","msg":"trace[391864803] transaction","detail":"{read_only:false; response_revision:84562298; number_of_response:1; }","duration":"3.182611741s","start":"2023-07-23T19:25:08.510Z","end":"2023-07-23T19:25:11.693Z","steps":["trace[391864803] 'process raft request'  (duration: 3.182522348s)"],"step_count":1}
{"level":"warn","ts":"2023-07-23T19:25:11.693Z","caller":"v3rpc/interceptor.go:197","msg":"request stats","start time":"2023-07-23T19:25:08.510Z","time spent":"3.182658946s","remote":"10.244.10.0:35117","response type":"/etcdserverpb.KV/Txn","request count":1,"request size":774,"response count":0,"response size":42,"request content":"compare:<key:\"omtm-xa/otmm-tcs-43792365-03ba-4c7e-a9e2-377c726cd850\" version:2 > success:<request_put:<key:\"omtm-xa/otmm-tcs-43792365-03ba-4c7e-a9e2-377c726cd850\" value_size:713 >> failure:<>"}
{"level":"info","ts":"2023-07-23T19:25:11.693Z","caller":"traceutil/trace.go:171","msg":"trace[939615482] transaction","detail":"{read_only:false; response_revision:84562327; number_of_response:1; }","duration":"3.177693367s","start":"2023-07-23T19:25:08.516Z","end":"2023-07-23T19:25:11.693Z","steps":["trace[939615482] 'process raft request'  (duration: 3.177610063s)"],"step_count":1}
...
{"level":"warn","ts":"2023-07-23T19:25:11.694Z","caller":"v3rpc/interceptor.go:197","msg":"request stats","start time":"2023-07-23T19:25:08.523Z","time spent":"3.170766547s","remote":"10.244.10.0:35117","response type":"/etcdserverpb.KV/Txn","request count":1,"request size":776,"response count":0,"response size":42,"request content":"compare:<key:\"omtm-xa/otmm-tcs-9a9517f8-3f23-4ea6-9bca-53074a76830d\" version:3 > success:<request_put:<key:\"omtm-xa/otmm-tcs-9a9517f8-3f23-4ea6-9bca-53074a76830d\" value_size:715 >> failure:<>"}
{"level":"warn","ts":"2023-07-23T19:25:11.694Z","caller":"v3rpc/interceptor.go:197","msg":"request stats","start time":"2023-07-23T19:25:08.523Z","time spent":"3.170741493s","remote":"10.244.10.0:35117","response type":"/etcdserverpb.Lease/LeaseGrant","request count":-1,"request size":-1,"response count":-1,"response size":-1,"request content":""}
{"level":"warn","ts":"2023-07-23T19:25:11.694Z","caller":"v3rpc/interceptor.go:197","msg":"request stats","start time":"2023-07-23T19:25:08.523Z","time spent":"3.170715509s","remote":"10.244.10.0:35117","response type":"/etcdserverpb.Lease/LeaseGrant","request count":-1,"request size":-1,"response count":-1,"response size":-1,"request content":""}
...
```
