### ISSUE TITLE
--socket-reuse-port and --socket-reuse-address These two flags have bugs

### ISSUE THREAD

**Issue by coderchuan** [etcd-io/etcd#16399]
### What happened?

--socket-reuse-port and --socket-reuse-address invalid in the configuration file, but are valid in the command flag

### What did you expect to happen?

--socket-reuse-port and --socket-reuse-address in the command flags should behave the same as in the configuration file

### Detail
**Following are the command flags，both node1 and node2 listening to the same port are running normally,  even though they use the same port, they work because of the --socket-reuse-port flag**
1.  etcd --name=node1 --force-new-cluster=false --initial-advertise-peer-urls=http://localhost:2380 --listen-peer-urls="http://localhost:2380" --advertise-client-urls="http://localhost:2379" --listen-client-urls="http://localhost:2379" --socket-reuse-port=true
2. etcd --name=node2 --force-new-cluster=false --initial-advertise-peer-urls=http://localhost:2380 --listen-peer-urls="http://localhost:2380" --advertise-client-urls="http://localhost:2379" --listen-client-urls="http://localhost:2379" --socket-reuse-port=true

**The following is the content of the configuration file in yaml format, running the first one is normal, running the second one will report address already in used, even with the socket-reuse-port flag enabled**
* node1, save as node1.yaml   ` etcd --config-file=node1.yaml`
  ```yaml
  name: node1
  force-new-cluster: false
  initial-advertise-peer-urls: http://localhost:2380
  listen-peer-urls: "http://localhost:2380"
  advertise-client-urls: "http://localhost:2379"
  listen-client-urls: "http://localhost:2379"
  socket-reuse-port: true
  ```
* node2,  save as node2.yaml    `etcd --config-file=node2.yaml`
  ```yaml
  name: node2
  force-new-cluster: false
  initial-advertise-peer-urls: http://localhost:2380
  listen-peer-urls: "http://localhost:2380"
  advertise-client-urls: "http://localhost:2379"
  listen-client-urls: "http://localhost:2379"
  socket-reuse-port: true
  ```

### Etcd version
```text
etcd Version: 3.5.9
Git SHA: bdbbde998
Go Version: go1.19.9
Go OS/Arch: linux/amd64
```

**Comment by jmhbnz** [comment]
Thanks for raising this @coderchuan. 

After some quick investigation it looks as though the config file might work as follows:

```yaml
socket-options:
  reuse-port: true
```

Can you please check and confirm? We may need to follow-up with an improvement to documentation or adjusting the structure so it follows all other configuration values.

**Comment by coderchuan** [comment]
> Thanks for raising this @coderchuan.
> 
> After some quick investigation it looks as though the config file might work as follows:
> 
> ```yaml
> socket-options:
>   reuse-port: true
> ```
> 
> Can you please check and confirm? We may need to follow-up with an improvement to documentation or adjusting the structure so it follows all other configuration values.
> 
> Edit: We could perhaps update the config file example to show how `socket-options` should be used as it is currently silent on it: https://github.com/etcd-io/etcd/blob/main/etcd.conf.yml.sample

**Tested using the following config in the config file still doesn't work**

* node1, save as node1.yaml , `etcd --config-file=node1.yaml`
  ```yaml
  name: node1
  force-new-cluster: false
  initial-advertise-peer-urls: http://localhost:2380
  listen-peer-urls: "http://localhost:2380"
  advertise-client-urls: "http://localhost:2379"
  listen-client-urls: "http://localhost:2379"
  socket-options:  
      reuse-port: true
  ```

* * node2, save as node2.yaml , `etcd --config-file=node2.yaml`
  ```yaml
  name: node2
  force-new-cluster: false
  initial-advertise-peer-urls: http://localhost:2380
  listen-peer-urls: "http://localhost:2380"
  advertise-client-urls: "http://localhost:2379"
  listen-client-urls: "http://localhost:2379"
  socket-options:  
      reuse-port: true
  ```
