### ISSUE TITLE
etcd cluster error

### ISSUE THREAD

**Issue by sumlittle** [etcd-io/etcd#18322]
### Bug report criteria

- [x] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [x] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [x] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [x] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

I tried to build a k8s cluster on rocky linux 9.4 based on VM deployment. The corresponding cluster information is as follows:
- Master
- Host name: k8s1
- IP address: 192.168.139.129

- Node
- Host name: k8s2
- IP address: 192.168.139.139
- Host name: k8s3
- IP address: 192.168.139.149

### What did you expect to happen?

When I checked the etcd cluster status after startup, I found:
Command--
etcdctl --endpoints=https://192.168.139.129:2379 --cacert=/etc/kubernetes/pki/etcd/etcd-ca.pem --cert=/etc/kubernetes/pki/etcd/etcd-peer.pem --key=/etc/kubernetes/pki/etcd/etcd-peer-key.pem member list

### How can we reproduce it (as minimally and precisely as possible)?

System version 
- rocky linux: 9.4

### Etcd version (please run commands below)

```console
etcdctl version
- etcdctl version: 3.5.12
- API version: 3.5
```

### Etcd configuration (command line flags or environment variables)

The corresponding k8s1 configuration file is as follows:
```
name: 'etcd1'
data-dir: '/var/lib/etcd'
listen-peer-urls: 'https://192.168.139.129:2380'
listen-client-urls: 'https://192.168.139.129:2379'
advertise-client-urls: 'https://192.168.139.129:2379'
initial-advertise-peer-urls: 'https://192.168.139.129:2380'
initial-cluster: 'etcd1=https://192.168.139.129:2380,

etcd2=https://192.168.139.139:2380,etcd3=https://192.168.139.149:2380'
initial-cluster-state: 'new'
initial-cluster-token: 'etcd-cluster'
client-transport-security:
  cert-file: /etc/kubernetes/pki/etcd/etcd-server.pem
  key-file: /etc/kubernetes/pki/etcd/etcd-server-key.pem
  client-cert-auth: true
  trusted-ca-file: /etc/kubernetes/pki/etcd/etcd-ca.pem
peer-transport-security:
  cert-file: /etc/kubernetes/pki/etcd/etcd-peer.pem
  key-file: /etc/kubernetes/pki/etcd/etcd-peer-key.pem
  peer-client-cert-auth: true
  trusted-ca-file: /etc/kubernetes/pki/etcd/etcd-ca.pem

```
The corresponding k8s2 configuration file is as follows:
```
name: 'etcd2'
data-dir: '/var/lib/etcd'
listen-peer-urls: 'https://192.168.139.139:2380'
listen-client-urls: 'https://192.168.139.139:2379'
advertise-client-urls: 'https://192.168.139.139:2379'
initial-advertise-peer-urls: 'https://192.168.139.139:2380'
initial-cluster: 'etcd1=https://192.168.139.129:2380,etcd2=https://192.168.139.139:2380,etcd3=https://192.168.139.149:2380'
initial-cluster-state: 'new'
initial-cluster-token: 'etcd-cluster'
client-transport-security:
  cert-file: /etc/kubernetes/pki/etcd/etcd-server.pem
  key-file: /etc/kubernetes/pki/etcd/etcd-server-key.pem
  client-cert-auth: true
  trusted-ca-file: /etc/kubernetes/pki/etcd/etcd-ca.pem
peer-transport-security:
  cert-file: /etc/kubernetes/pki/etcd/etcd-peer.pem
  key-file: /etc/kubernetes/pki/etcd/etcd-peer-key.pem
  peer-client-cert-auth: true
  trusted-ca-file: /etc/kubernetes/pki/etcd/etcd-ca.pem
```
The corresponding k8s3 configuration file is as follows:
```
name: 'etcd3'
data-dir: '/var/lib/etcd'
listen-peer-urls: 'https://192.168.139.149:2380'
listen-client-urls: 'https://192.168.139.149:2379'
advertise-client-urls: 'https://192.168.139.149:2379'
initial-advertise-peer-urls: 'https://192.168.139.149:2380'
initial-cluster: 'etcd1=https://192.168.139.129:2380,etcd2=https://192.168.139.139:2380,etcd3=https://192.168.139.149:2380'
initial-cluster-state: 'new'
initial-cluster-token: 'etcd-cluster'
client-transport-security:
  cert-file: /etc/kubernetes/pki/etcd/etcd-server.pem
  key-file: /etc/kubernetes/pki/etcd/etcd-server-key.pem
  client-cert-auth: true
  trusted-ca-file: /etc/kubernetes/pki/etcd/etcd-ca.pem
peer-transport-security:
  cert-file: /etc/kubernetes/pki/etcd/etcd-peer.pem
  key-file: /etc/kubernetes/pki/etcd/etcd-peer-key.pem
  peer-client-cert-auth: true
  trusted-ca-file: /etc/kubernetes/pki/etcd/etcd-ca.pem
```

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

```console
etcdctl --endpoints=https://192.168.139.129:2379 --cacert=/etc/kubernetes/pki/etcd/etcd-ca.pem --cert=/etc/kubernetes/pki/etcd/etcd-peer.pem --key=/etc/kubernetes/pki/etcd/etcd-peer-key.pem member list
```

### Relevant log output

```Shell
etcdctl --endpoints=https://192.168.139.129:2379 --cacert=/etc/kubernetes/pki/etcd/etcd-ca.pem --cert=/etc/kubernetes/pki/etcd/etcd-peer.pem --key=/etc/kubernetes/pki/etcd/etcd-peer-key.pem member list
{"level":"warn","ts":"2024-07-15T16:55:23.659995+0800","logger":"etcd-client","caller":"v3@v3.5.12/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000ba8c0/192.168.139.129:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Error: context deadline exceeded
```
