### ISSUE TITLE
errors.Is not work for rpctypes.ErrGRPCxxxx

### ISSUE THREAD

**Issue by cruvie** [etcd-io/etcd#18493]
### What would you like to be added?

support errors.Is for error generated from client

or provide a method to compare two errors

### Why is this needed?

```go
func TestErr(t *testing.T) {
	client, err := clientv3.New(clientv3.Config{
		Endpoints: []string{"127.0.0.1:2379"},
		Username:  "notexistuser",
		Password:  "",
	})
	if err != nil {
		panic(err)
	}
	resp, err := client.AuthStatus(context.Background())
	log.Println(resp)
	if err != nil {
		if errors.Is(err, rpctypes.ErrGRPCUserEmpty) {
			//should enter to this branch
			log.Println("user not exist")
		}
		log.Println(err)//etcdserver: user name is empty
	}
}

```
go 1.23.0
go.etcd.io/etcd/client/v3 v3.5.15

**Comment by ArkaSaha30** [comment]
Can you please help with the steps to reproduce the issue?

**Comment by cruvie** [comment]
@ArkaSaha30 I have updated the reproduce code above
use a not exist user create etcd clietn
the return err should match `if errors.Is(err, rpctypes.ErrGRPCUserEmpty) {`, but it skiped

**Comment by ivanvc** [comment]
@cruvie, please try using `rpctypes.ErrUserNotFound`.

However, I think instantiating the client should return an authentication error before it gets to `client.AuthStatus`

**Comment by cruvie** [comment]
@ivanvc `rpctypes.ErrUserNotFound` not works, too

> I think instantiating the client should return an authentication error before it gets to client.AuthStatus

I agree

**Comment by ivanvc** [comment]
@cruvie, got it. The issue is that I'm not able to reproduce. If I start a new cluster, enable authentication, and then run the snippet you provided:

```golang
        client, err := clientv3.New(clientv3.Config{
		Endpoints: []string{"127.0.0.1:2379"},
		Username:  "notexistuser",
		Password:  "",
	})
	if errors.Is(err, rpctypes.ErrGRPCAuthFailed) {
		log.Fatal(err)
	}
```

It fails with `ErrAuthFailed`, as expected. I'd appreciate it if you could provide how you have your setup so we can reproduce it.

**Comment by cruvie** [comment]
@ivanvc here are my steps
run docker-compose
```yml
version: "3.9"
services:
# https://etcd.io/docs/v3.5/op-guide/container/
  etcd:
    image: quay.io/coreos/etcd:v3.5.15-arm64
    container_name: etcd
    command:
      [
        "/usr/local/bin/etcd",
        "--data-dir=/etcd-data",
        "--name=node1",
        "--initial-advertise-peer-urls=http://etcd:2380",
        "--listen-peer-urls=http://0.0.0.0:2380",
        "--advertise-client-urls=http://etcd:2379",
        "--listen-client-urls=http://0.0.0.0:2379",
        "--initial-cluster=node1=http://etcd:2380"
      ]
    restart: unless-stopped
    ports:
      - "2379:2379"
      - "2380:2380"
```
run code 
```go

func TestErr(t *testing.T) {
	client, err := clientv3.New(clientv3.Config{
		Endpoints: []string{"127.0.0.1:2379"},
		Username:  "notexistuser",
		Password:  "",
	})
	if err != nil {
		panic(err)
	}
	{
		_, err := client.UserAdd(context.Background(), "root", "root")
		if err != nil {
			panic(err)
		}
		_, err = client.RoleAdd(context.Background(), "root")
		if err != nil {
			panic(err)
		}
		_, err = client.UserGrantRole(context.Background(), "root", "root")
		if err != nil {
			panic(err)
		}
		_, err = client.AuthEnable(context.Background())
		if err != nil {
			panic(err)
		}
	}
	resp, err := client.AuthStatus(context.Background())
	log.Println(resp)
	if err != nil {
		//if errors.Is(err, rpctypes.ErrGRPCUserEmpty) {
		if errors.Is(err, rpctypes.ErrUserNotFound) {
			//should enter to this branch
			log.Println("user not exist")
		}
		log.Println(err) //etcdserver: user name is empty
	}
}
```
output
```sh
=== RUN   TestErr
{"level":"warn","ts":"2024-09-11T11:58:04.374368+0800","logger":"etcd-client","caller":"v3@v3.5.14/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x140002425a0/127.0.0.1:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty"}
2024/09/11 11:58:04 <nil>
2024/09/11 11:58:09 etcdserver: user name is empty
--- PASS: TestErr (9.02s)
PASS
```
