### ISSUE TITLE
Enable periodic integration tests in prow

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/etcd#19051]
### What would you like to be added?

We recently enabled periodic integration tests for 1 CPU in prow (https://github.com/kubernetes/test-infra/pull/33894 / https://github.com/etcd-io/etcd/pull/18976#issuecomment-2510156973). After seeing them running for the last week (https://testgrid.k8s.io/sig-etcd-periodics), we should also enable 2 CPU and 4 CPU jobs.

As a reference, take a look at the pull request: https://github.com/kubernetes/test-infra/pull/33894/files

The current definitions for the presubmit jobs for 2 and 4 CPUs are here:
* [2 CPUs AMD64](https://github.com/kubernetes/test-infra/blob/c00c8c65084d11d721aba2ecda8f0a8a3d7ebad9/config/jobs/etcd/etcd-presubmits.yaml#L328-L356)
* [2 CPUs ARM64](https://github.com/kubernetes/test-infra/blob/c00c8c65084d11d721aba2ecda8f0a8a3d7ebad9/config/jobs/etcd/etcd-presubmits.yaml#L358-L389)
* [4 CPUs AMD64](https://github.com/kubernetes/test-infra/blob/c00c8c65084d11d721aba2ecda8f0a8a3d7ebad9/config/jobs/etcd/etcd-presubmits.yaml#L391-L419)
* [4 CPUs ARM64](https://github.com/kubernetes/test-infra/blob/c00c8c65084d11d721aba2ecda8f0a8a3d7ebad9/config/jobs/etcd/etcd-presubmits.yaml#L421-L452)

The periodic job definition is very similar. However, we need the following changes:
1. Replace the "pull" prefix from the job name with "ci"
2. Drop `always_run` and `branches`, i.e.,
    ```yaml
    always_run: true
    branches:
      - main
      - release-3.5
    ```
3. Add `interval` set to 24h and `extra_refs`, i.e.
    ```yaml
      interval: 24h
      extra_refs:
        - org: etcd-io
          repo: etcd
          base_ref: main
    ```

**NOTE** that this pull request should be opened in the [kuberentes/test-infra repository](https://github.com/kubernetes/test-infra), and it should modify the [`config/jobs/etcd/etcd-periodics.yaml` file](https://github.com/ivanvc/test-infra/blob/fc8f7f745f96286ef412b71ac0cec09ed3588cd7/config/jobs/etcd/etcd-periodics.yaml).

### Why is this needed?

To improve test stance and help identify flaky tests.
