### ISSUE TITLE
etcd raftindex never consistent

### ISSUE THREAD

**Issue by hongliang5316** [etcd-io/etcd#19701]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

<img width="1670" alt="Image" src="https://github.com/user-attachments/assets/d0e55e09-60d7-4f85-9ace-cb0e6ee1a8d2" />
`server logs:`

{"level":"warn","ts":"2025-04-03T08:59:21.650442+0800","caller":"auth/store.go:1183","msg":"invalid auth token","token":"epqYPGKRnYXOGunN.50653"}
{"level":"warn","ts":"2025-04-03T08:59:28.227083+0800","caller":"auth/store.go:1183","msg":"invalid auth token","token":"JWhaPozgpsUbIhrs.50863"}
{"level":"warn","ts":"2025-04-03T08:59:48.4305+0800","caller":"auth/store.go:1183","msg":"invalid auth token","token":"LMUDarkiUhYPgYgl.51574"}
`client error:`
The client's watcher resp is often canceled
{"level":"warn","ts":"2025-04-03T10:24:55.036264+0800","logger":"etcd-client","caller":"v3/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00051a780/{ip}:12379","attempt":0,"error":"rpc error: code = Unauthenticated desc = etcdserver: invalid auth token"}
{"level":"warn","ts":"2025-04-03T10:25:02.132197+0800","logger":"etcd-client","caller":"v3/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00051a780/{ip}:12379","attempt":0,"error":"rpc error: code = Unauthenticated desc = etcdserver: invalid auth token"}
{"level":"warn","ts":"2025-04-03T10:25:02.217804+0800","logger":"etcd-client","caller":"v3/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00051a780/{ip}:12379","attempt":0,"error":"rpc error: code = Unauthenticated desc = etcdserver: invalid auth token"}
{"level":"warn","ts":"2025-04-03T10:25:07.030061+0800","logger":"etcd-client","caller":"v3/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00051a780/{ip}:12379","attempt":0,"error":"rpc error: code = Unauthenticated desc = etcdserver: invalid auth token"}
I am very sure that the username and password entered by the client are correct.

### What did you expect to happen?

No server or client errors

### How can we reproduce it (as minimally and precisely as possible)?

ETCD_NAME=etcd01
ETCD_DATA_DIR=/data/etcd
ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:12379
ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
ETCD_ADVERTISE_CLIENT_URLS=http://{ip}:12379
ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.0.0.6:2380
ETCD_INITIAL_CLUSTER=etcd01=http://10.0.0.6:2380,etcd02=http://10.2.0.8:2380,etcd03=http://10.1.0.17:2380
ETCD_INITIAL_CLUSTER_STATE=existing
ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
ETCD_MAX_REQUEST_BYTES=5242880
ETCD_LOG_LEVEL=info
ETCD_LOG_OUTPUTS=/data/log/etcd/etcd.log
ETCD_AUTH_TOKEN=simple
ETCD_AUTH_TOKEN_TTL=3600

ETCD_NAME=etcd02
ETCD_DATA_DIR=/data/etcd
ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:12379
ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
ETCD_ADVERTISE_CLIENT_URLS=http://{ip}:12379
ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.2.0.8:2380
ETCD_INITIAL_CLUSTER=etcd01=http://10.0.0.6:2380,etcd02=http://10.2.0.8:2380,etcd03=http://10.1.0.17:2380
ETCD_INITIAL_CLUSTER_STATE=existing
ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
ETCD_MAX_REQUEST_BYTES=5242880
ETCD_LOG_LEVEL=info
ETCD_LOG_OUTPUTS=/data/log/etcd/etcd.log
ETCD_AUTH_TOKEN=simple
ETCD_AUTH_TOKEN_TTL=3600

ETCD_NAME=etcd03
ETCD_DATA_DIR=/data/etcd
ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:12379
ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
ETCD_ADVERTISE_CLIENT_URLS=http://{ip}:12379
ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.1.0.17:2380
ETCD_INITIAL_CLUSTER=etcd01=http://10.0.0.6:2380,etcd02=http://10.2.0.8:2380,etcd03=http://10.1.0.17:2380
ETCD_INITIAL_CLUSTER_STATE=existing
ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
ETCD_MAX_REQUEST_BYTES=5242880
ETCD_LOG_LEVEL=info
ETCD_LOG_OUTPUTS=/data/log/etcd/etcd.log
ETCD_AUTH_TOKEN=simple
ETCD_AUTH_TOKEN_TTL=3600

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here
etcd Version: 3.5.12
Git SHA: e7b3bb6cc
Go Version: go1.23.7
Go OS/Arch: linux/amd64
$ etcdctl version
# paste output here
```
etcdctl version: 3.5.19
API version: 3.5
</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```Shell

```

**Comment by jberkus** [comment]
Hey, can you retry your issue on the patch version of 3.5?  That is, 3.5.21?

**Comment by hongliang5316** [comment]
@jberkus 
Hello, it not ok, but i disable auth, everything is fine.
# enable auth
<img width="1469" alt="Image" src="https://github.com/user-attachments/assets/21d306b1-494e-4391-9dda-ada0ff63f2c3" />

# disable auth

<img width="1469" alt="Image" src="https://github.com/user-attachments/assets/00b124c2-4817-4882-b9a3-bd2b57c4d483" />

**Comment by joshjms** [comment]
I see. @hongliang5316, I'll try to help with this issue 😄 . I'll try to replicate it first, I hope you don't mind if I have any inquiries.

**Comment by joshjms** [comment]
Hi @hongliang5316 , can you tell me the exact command you used and what you did to enable and disable auth?

**Comment by hongliang5316** [comment]
@joshjms 

`etcdctl auth disable`

**Comment by joshjms** [comment]
Ok, I managed to reproduce the issue.

**Comment by joshjms** [comment]
### Create a Cluster

```yaml!
services:
  etcd01:
    image: etcd:3.5.21-0
    container_name: etcd01
    networks:
      etcd_net:
        aliases:
          - etcd01
    ports:
      - "12379:2379"
      - "12380:2380"
    command: >
      etcd
      --name=etcd01
      --data-dir=/etcd-data
      --listen-client-urls=http://0.0.0.0:2379
      --advertise-client-urls=http://etcd01:2379
      --listen-peer-urls=http://0.0.0.0:2380
      --initial-advertise-peer-urls=http://etcd01:2380
      --initial-cluster=etcd01=http://etcd01:2380,etcd02=http://etcd02:2380,etcd03=http://etcd03:2380
      --initial-cluster-state=new
      --initial-cluster-token=etcd-cluster
      --auth-token=simple
      --auth-token-ttl=3600

  etcd02:
    image: etcd:3.5.21-0
    container_name: etcd02
    networks:
      etcd_net:
        aliases:
          - etcd02
    ports:
      - "22379:2379"
      - "22380:2380"
    command: >
      etcd
      --name=etcd02
      --data-dir=/etcd-data
      --listen-client-urls=http://0.0.0.0:2379
      --advertise-client-urls=http://etcd02:2379
      --listen-peer-urls=http://0.0.0.0:2380
      --initial-advertise-peer-urls=http://etcd02:2380
      --initial-cluster=etcd01=http://etcd01:2380,etcd02=http://etcd02:2380,etcd03=http://etcd03:2380
      --initial-cluster-state=new
      --initial-cluster-token=etcd-cluster
      --auth-token=simple
      --auth-token-ttl=3600

  etcd03:
    image: etcd:3.5.21-0
    container_name: etcd03
    networks:
      etcd_net:
        aliases:
          - etcd03
    ports:
      - "32379:2379"
      - "32380:2380"
    command: >
      etcd
      --name=etcd03
      --data-dir=/etcd-data
      --listen-client-urls=http://0.0.0.0:2379
      --advertise-client-urls=http://etcd03:2379
      --listen-peer-urls=http://0.0.0.0:2380
      --initial-advertise-peer-urls=http://etcd03:2380
      --initial-cluster=etcd01=http://etcd01:2380,etcd02=http://etcd02:2380,etcd03=http://etcd03:2380
      --initial-cluster-state=new
      --initial-cluster-token=etcd-cluster
      --auth-token=simple
      --auth-token-ttl=3600
  client:
    image: etcd:3.5.21-0
    container_name: etcd-client
    networks:
      etcd_net:
        aliases:
          - etcd-client
    depends_on:
      - etcd01
      - etcd02
      - etcd03
    tty: true
    stdin_open: true
    entrypoint: /bin/sh

networks:
  etcd_net:
    driver: bridge
```

In the terminal:

```shell!
docker attach etcd-client
```

### Create User

```shell!
etcdctl \
    --endpoints=http://etcd01:2379 \
    user add root:joshjmswashere \
    --interactive=false
    
etcdctl \
    --endpoints=http://etcd01:2379 \
    user grant-role root root
```

### Enable Auth
```shell!
etcdctl \
    --endpoints=http://etcd01:2379 \
    auth enable
```

### Show Status Table

```shell!
etcdctl \
  --endpoints=http://etcd01:2379,http://etcd02:2379,http://etcd03:2379 \
  --user root:joshjmswashere \
  endpoint status --write-out=table
```

#### Result

```
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|      ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| http://etcd01:2379 | b8b747c74aaea686 |  3.5.21 |   20 kB |      true |      false |         2 |         17 |                 17 |        |
| http://etcd02:2379 |  b3504381e8ba3cb |  3.5.21 |   20 kB |     false |      false |         2 |         18 |                 18 |        |
| http://etcd03:2379 | f572fdfc5cb68406 |  3.5.21 |   20 kB |     false |      false |         2 |         19 |                 19 |        |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```

### Disable Auth

```sh!
etcdctl \
    --endpoints=http://etcd01:2379 \ 
    auth disable
```

### Show Status Table

```shell!
etcdctl \
  --endpoints=http://etcd01:2379,http://etcd02:2379,http://etcd03:2379 \
  --user root:joshjmswashere \
  endpoint status --write-out=table
```

#### Result

```
{"level":"warn","ts":"2025-04-13T01:31:55.499544Z","logger":"etcd-client","caller":"v3@v3.5.21/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000024000/etcd01:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
{"level":"warn","ts":"2025-04-13T01:31:55.500523Z","logger":"etcd-client","caller":"v3@v3.5.21/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000024000/etcd01:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
{"level":"warn","ts":"2025-04-13T01:31:55.503404Z","logger":"etcd-client","caller":"v3@v3.5.21/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000024000/etcd01:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
{"level":"warn","ts":"2025-04-13T01:31:55.505539Z","logger":"etcd-client","caller":"v3@v3.5.21/retry_interceptor.go:63","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000024000/etcd01:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: authentication is not enabled"}
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|      ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| http://etcd01:2379 | b8b747c74aaea686 |  3.5.21 |   20 kB |      true |      false |         2 |         22 |                 22 |        |
| http://etcd02:2379 |  b3504381e8ba3cb |  3.5.21 |   20 kB |     false |      false |         2 |         22 |                 22 |        |
| http://etcd03:2379 | f572fdfc5cb68406 |  3.5.21 |   20 kB |     false |      false |         2 |         22 |                 22 |        |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```
