### ISSUE TITLE
Slowly increasing memory usage

### ISSUE THREAD

**Issue by tarnfeld** [etcd-io/etcd#780]
I've been running a 3 node pre-production cluster over the past couple of weeks for housing a small amount of internal data, and oddly the memory usage has been growing at an alarming rate.

Currently, there are 56 keys (an 141 nodes in total, some of which are directories). The data within each key is pretty small (handful of bytes). The cluster is serving a very small amount of writes (one a day, maybe) and also a handful of reads (a couple of requests a minute, maybe a few more).

This is the memory graph for `etcd` on each node in the cluster (the blue lines are etcd)...

![screen shot 2014-05-09 at 18 51 13](https://cloud.githubusercontent.com/assets/217279/2931374/b1a0481a-d7a2-11e3-8c64-dea477ad6d7d.png)

_Note the drop around may 4th was before the cluster was up and running, so ignore anything prior to that date._
#### Configuration file

``` toml
#
# This configuration file is managed by chef.
#

addr = "XX.XX.XX.XX:4001"
bind_addr = "XX.XX.XX.XX:4001"
ca_file = ""
cert_file = ""
cors = []
data_dir = "/var/lib/etcd"
discovery = ""
key_file = ""
max_cluster_size = 9
max_result_buffer = 1024
max_retry_attempts = 3
name = "XX"
peers = ["ZZ:7001","YY:7001","XX:7001"]
peers_file = ""
snapshot = false
verbose = false
very_verbose = false

[peer]
addr = "XX.XX.XX.XX:7001"
bind_addr = "XX.XX.XX.XX:7001"
ca_file = ""
cert_file = ""
election_timeout = 600
heartbeat_interval = 200
key_file = ""
```

It's worth noting that I do have snapshotting disabled, this was deliberate to see the effect of not compacting the log, though would this have much of an effect when the cluster is serving almost zero writes?

Interestingly, the logs do seem to have a fair amount of activity..

``` bash
$ cat /var/log/etcd/etcd.log | grep "election timeout" | wc -l
1390
$ cat /var/log/etcd/etcd.log | grep "leader changed" | wc -l
1184
```
