### ISSUE TITLE
Clean install of CoreOS stable (today) and etcd failing to start

### ISSUE THREAD

**Issue by chriscowley** [etcd-io/etcd#916]
After boot:

```
core@coreos0 ~ $ ps -edaf|grep etcd
core       882   473  0 21:12 pts/0    00:00:00 grep --colour=auto etcd
core@coreos0 ~ $ sudo systemctl status etcd
● etcd.service - etcd
   Loaded: loaded (/usr/lib64/systemd/system/etcd.service; disabled)
  Drop-In: /run/systemd/system/etcd.service.d
           └─20-cloudinit.conf
   Active: activating (auto-restart) (Result: exit-code) since Fri 2014-08-01 21:12:57 UTC; 8s ago
  Process: 928 ExecStart=/usr/bin/etcd (code=exited, status=1/FAILURE)
 Main PID: 928 (code=exited, status=1/FAILURE)

Aug 01 21:13:35 coreos0 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Aug 01 21:13:35 coreos0 systemd[1]: Unit etcd.service entered failed state.
```

Run `sudo systemctl start etcd` gives no output

Afterwards:

```
core@coreos0 ~ $ sudo systemctl status etcd
● etcd.service - etcd
   Loaded: loaded (/usr/lib64/systemd/system/etcd.service; disabled)
  Drop-In: /run/systemd/system/etcd.service.d
           └─20-cloudinit.conf
   Active: activating (auto-restart) (Result: exit-code) since Fri 2014-08-01 21:13:35 UTC; 5s ago
  Process: 928 ExecStart=/usr/bin/etcd (code=exited, status=1/FAILURE)
 Main PID: 928 (code=exited, status=1/FAILURE)

Aug 01 21:13:35 coreos0 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Aug 01 21:13:35 coreos0 systemd[1]: Unit etcd.service entered failed state.
```

user-data:

```
#cloud-config

hostname: coreos0
ssh_authorized_keys:
 - ssh-rsa ... <blah, blah,blah>
coreos:
  etcd:
    name: coreos0
    discovery: https://discovery.etcd.io/<token>
    addr: <dhcp-assigned-ip>:4001
    peer-addr: <dhcp-assigned-ip>:7001
```

`/run/systemd/system/etcd.service.d/20-cloudinit.conf` seems to have been populated successfully, but `etcd` is 100% dead
