### ISSUE TITLE
File based user configuration

### ISSUE THREAD

**Issue by ercliou** [etcd-io/etcd#9779]
I'd like to suggest seeding pre-populated users through a config file.
This is particularly useful when habilitating CN authentication (even more when we're able to create user without passwords https://github.com/coreos/etcd/issues/9590).
So we wouldn't have to mess with the API.

Currently, when I need to create some users. The process looks like this:
```
echo rootpasswd | etcdctl user add root --interactive false

etcdctl auth enable

gen_passwd | etcdctl --user root:rootpasswd --interactive false user add kubernetes 
etcdctl --user root:rootpasswd user grant-role kubernetes-role root
etcdctl --user root:rootpasswd role grant-permission kubernetes-role --prefix=true readwrite /registry/

gen_passwd | etcdctl --user root:rootpasswd --interactive false user add calico
etcdctl --user root:rootpasswd user grant-role calico-role root
etcdctl --user root:rootpasswd role grant-permission calico-role --prefix=true readwrite /calico/
```

The file based configuration could look something like this and could be passed as an init flag `--user-config $FILE`:
```yaml
users:
- name: root
  password: rootpasswd
- name: kubernetes
  role: kubernetes-role
- name: calico
  role: calico-role
roles:
- name: calico-role
  access: readwrite
  prefix: /calico/
- name: kubernetes-role
  access: readwrite
  prefix: /registry/
```
