### ISSUE TITLE
watch through grpc proxy result in delay or miss event

### ISSUE THREAD

**Issue by clusc** [etcd-io/etcd#9988]
Hi,

We've noticed an issue where client receives delayed event(up to a few min) or even missed event when watching through the grpc proxy. The same code works perfectly fine when watching through etcd cluster directly. There's no obvious error log I can find on both server and proxy side. Can you help us investigate where the issue is?

Setup: 20 clients, 3 grpc proxy, 6 etcd node cluster
Version: v3.3.9 (client, proxy and server)

Let us know what additional info needed.

Thanks,

Eric

**Comment by xiang90** [comment]
We need to know how to reproduce the issue. Ideally with detailed steps or a script.

**Comment by clusc** [comment]
Steps to reproduce:
1. Create a 6 node etcd cluster(v3.3.9) onto GKE(1.9.6-gke.1) using etcd-operator.
    *Given the issue can't be reproduced if we watch through the cluster directly, I'll skip the cluster setup details, but I can provide later if needed.*
2. Deploy gRPC proxy using the following YAML:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: etcd-proxy
  name: etcd-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: etcd-proxy
  template:
    metadata:
      labels:
        app: etcd-proxy
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: etcd-proxy
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          /usr/local/bin/etcd grpc-proxy start --advertise-client-url="$POD_IP:2379" --listen-addr="0.0.0.0:2379" --resolver-prefix="___grpc_proxy_endpoint" --resolver-ttl=60 --endpoints="etcd-cluster-client.default.svc.cluster.local:2379"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: gcr.io/etcd-development/etcd:v3.3.9
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 2379
          timeoutSeconds: 1
        name: etcd-proxy
        ports:
        - containerPort: 2379
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 2379
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "3"
            memory: 10Gi
          requests:
            cpu: "3"
            memory: 10Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        cloud.google.com/gke-nodepool: proxy-pool
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
3. Create services that binds etcd and grpc proxy to node port:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-cluster-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32379
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
    etcd_cluster: etcd-cluster
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-proxy-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32380
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd-proxy
  sessionAffinity: None
  type: NodePort
```
4. Create GCP internal LB that points to 32379 & 32380
5. Wrote a simple go binary that watch a specific key, gist looks like:
```go
func refresh(ctx context.Context, c *etcd.Client, etcdEndpoint, etcdRecordPath string) {
	for {
		wch := c.Watch(ctx, etcdRecordPath, etcd.WithCreatedNotify())

	loop:
		for wresp := range wch {
			switch {
			case wresp.Canceled:
				glog.Errorf("watch canceled: %v", wresp.Err())
				// Break to let etcd client to reconnect.
				break loop
			case len(wresp.Events) > 0:
				glog.Infof("received events: %v", wresp.Events)
				// Get the value of the latest revision, and attempt to update.
				var kv *mvccpb.KeyValue
				for _, evt := range wresp.Events {
					if evt.Type != etcd.EventTypePut {
						continue
					}
					if kv == nil || evt.Kv.ModRevision > kv.ModRevision {
						kv = evt.Kv
					}
				}

				if kv == nil {
					continue
				}

				epoch, err := parseEpoch(kv.Value)
				if err != nil {
					// TODO(ben.ulmer):Add a metric to track parsing failures.
					glog.Errorf("failed to parse epoch: %v", err)
					continue
				}
				glog.Infof("got epoch: %d", epoch)
			case wresp.Created:
				glog.Info("received created")
				// Load initial value on the created event in order to avoid
				// missing an update which occured between initial loading and
				// watcher creation.
				epoch, err := fetchEpoch(ctx, c, etcdRecordPath)
				if err != nil {
					glog.Errorf("failed to read epoch: %v", err)
					continue
				}
				glog.Infof("got epoch: %d", epoch)
			}
		}

		c.Close()
		for {
			var err error
			c, err = etcd.New(etcd.Config{
				Endpoints:            []string{etcdEndpoint},
				DialTimeout:          etcdDialTimeout,
				DialKeepAliveTime:    etcdDialKeepAliveTime,
				DialKeepAliveTimeout: etcdDialKeepAliveTimeout,
			})
			if err == nil {
				break
			}
			glog.Errorf("failed to connect to etcd: %v", err)
			time.Sleep(etcdDialRetryInterval)
		}
	}
}
```
Note the `etcdEndpoint` is the internal LB's DNS address to the grpc proxy.
6. Deploy 20 client binaries(in our case, in another GKE cluster). When they all started, we see exactly 20 `received created` log messages.
7. Write some data to the watched key(through `etcdctl`)
8. Only 18/20 client receives the update(`received events` log line), and there's 7min delay between the first and last event received.
9. The same client code, if we replace `etcdEndpoint` with LB's DNS address to the cluster itself, we get 20 `received events` log line at the exact same time.
